package persistence

// schemaForeignKeyExtensions 返回无法由 Ent edge 表达、仍需 PostgreSQL 原生约束维护的例外。
// 普通单字段外键已经迁入 ent/schema；这里仅保留复合关系和跨聚合约束。
func schemaForeignKeyExtensions() []schemaForeignKeyDefinition {
	exceptions := map[string]struct{}{
		"fk_battle_turn_submission_battle_id_side":                        {},
		"fk_battle_turn_submission_battle_id_state_version":               {},
		"fk_player_character_profession_skill_player_character__f52b2e54": {},
		"fk_player_character_quest_objective_player_character_i_d886e8fe": {},
		"fk_player_character_team_member_skill_team_id_member_p_96c52a3b": {},
		"fk_player_character_team_member_stat_team_id_member_po_6eb75f33": {},
		"fk_active_player_character_account_id_id":                        {},
		"fk_active_player_character_team_player_character_id_id":          {},
		"fk_battle_participant_reservation_player_character_id_id":        {},
		"fk_battle_runtime_lease_battle_id_id":                            {},
		"fk_battle_authoritative_summary_battle_id_id":                    {},
		"fk_player_character_equipment_loadout_state_id_id":               {},
	}
	filtered := make([]schemaForeignKeyDefinition, 0, len(exceptions))
	for _, definition := range schemaForeignKeyDefinitions {
		if _, keep := exceptions[definition.name]; keep {
			filtered = append(filtered, definition)
		}
	}
	return filtered
}

// schemaIndexDefinition 描述 Ent 无法完整表达的 PostgreSQL 索引。
type schemaIndexDefinition struct {
	name      string
	statement string
}

// schemaForeignKeyDefinition 描述需要在所有 Ent 表创建后补齐的 PostgreSQL 外键。
type schemaForeignKeyDefinition struct {
	table      string
	name       string
	definition string
}

var schemaIndexDefinitions = []schemaIndexDefinition{
	{name: "uk_rpg_location_default_spawn", statement: "CREATE UNIQUE INDEX IF NOT EXISTS uk_rpg_location_default_spawn ON public.rpg_location USING btree (default_spawn) WHERE default_spawn"},
	{name: "uk_active_player_character_player_character_id", statement: "CREATE UNIQUE INDEX IF NOT EXISTS uk_active_player_character_player_character_id ON public.active_player_character USING btree (player_character_id)"},
	{name: "uk_active_player_character_team_team_id", statement: "CREATE UNIQUE INDEX IF NOT EXISTS uk_active_player_character_team_team_id ON public.active_player_character_team USING btree (team_id)"},
	{name: "uk_admin_account_display_name", statement: "CREATE UNIQUE INDEX IF NOT EXISTS uk_admin_account_display_name ON public.admin_account USING btree (display_name)"},
	{name: "uk_admin_account_username_key", statement: "CREATE UNIQUE INDEX IF NOT EXISTS uk_admin_account_username_key ON public.admin_account USING btree (username_key)"},
	{name: "idx_admin_audit_log_actor_account_id_created_at_id", statement: "CREATE INDEX IF NOT EXISTS idx_admin_audit_log_actor_account_id_created_at_id ON public.admin_audit_log USING btree (actor_account_id, created_at, id)"},
	{name: "idx_admin_audit_log_created_at_id", statement: "CREATE INDEX IF NOT EXISTS idx_admin_audit_log_created_at_id ON public.admin_audit_log USING btree (created_at, id)"},
	{name: "uk_admin_audit_log_sequence", statement: "CREATE UNIQUE INDEX IF NOT EXISTS uk_admin_audit_log_sequence ON public.admin_audit_log USING btree (sequence)"},
	{name: "idx_admin_login_attempt_account_id_occurred_at_id", statement: "CREATE INDEX IF NOT EXISTS idx_admin_login_attempt_account_id_occurred_at_id ON public.admin_login_attempt USING btree (account_id, occurred_at DESC, id)"},
	{name: "idx_admin_login_attempt_username_digest_occurred_at_id", statement: "CREATE INDEX IF NOT EXISTS idx_admin_login_attempt_username_digest_occurred_at_id ON public.admin_login_attempt USING btree (username_digest, occurred_at DESC, id)"},
	{name: "idx_administration_audit_log_actor_account_id_created_at_id", statement: "CREATE INDEX IF NOT EXISTS idx_administration_audit_log_actor_account_id_created_at_id ON public.administration_audit_log USING btree (actor_account_id, created_at, id)"},
	{name: "idx_administration_audit_log_created_at_id", statement: "CREATE INDEX IF NOT EXISTS idx_administration_audit_log_created_at_id ON public.administration_audit_log USING btree (created_at, id)"},
	{name: "uk_administration_audit_log_sequence", statement: "CREATE UNIQUE INDEX IF NOT EXISTS uk_administration_audit_log_sequence ON public.administration_audit_log USING btree (sequence)"},
	{name: "idx_administration_outbox_created_at_id", statement: "CREATE INDEX IF NOT EXISTS idx_administration_outbox_created_at_id ON public.administration_outbox USING btree (created_at, id) WHERE (published_at IS NULL)"},
	{name: "uk_asset_object_key", statement: "CREATE UNIQUE INDEX IF NOT EXISTS uk_asset_object_key ON public.asset USING btree (object_key)"},
	{name: "idx_asset_owner_account_id_status_created_at_id", statement: "CREATE INDEX IF NOT EXISTS idx_asset_owner_account_id_status_created_at_id ON public.asset USING btree (owner_account_id, status, created_at DESC, id DESC)"},
	{name: "uk_game_ability_code", statement: "CREATE UNIQUE INDEX IF NOT EXISTS uk_game_ability_code ON public.game_ability USING btree (code)"},
	{name: "uk_game_battle_clause_code", statement: "CREATE UNIQUE INDEX IF NOT EXISTS uk_game_battle_clause_code ON public.game_battle_clause USING btree (code)"},
	{name: "uk_game_battle_format_code", statement: "CREATE UNIQUE INDEX IF NOT EXISTS uk_game_battle_format_code ON public.game_battle_format USING btree (code)"},
	{name: "uk_game_battle_mechanic_code", statement: "CREATE UNIQUE INDEX IF NOT EXISTS uk_game_battle_mechanic_code ON public.game_battle_mechanic USING btree (code)"},
	{name: "uk_game_battle_restriction_code", statement: "CREATE UNIQUE INDEX IF NOT EXISTS uk_game_battle_restriction_code ON public.game_battle_restriction USING btree (code)"},
	{name: "uk_game_creature_ability_creature_id_ability_id", statement: "CREATE UNIQUE INDEX IF NOT EXISTS uk_game_creature_ability_creature_id_ability_id ON public.game_creature_ability USING btree (creature_id, ability_id)"},
	{name: "uk_game_creature_code", statement: "CREATE UNIQUE INDEX IF NOT EXISTS uk_game_creature_code ON public.game_creature USING btree (code)"},
	{name: "uk_game_creature_species_id", statement: "CREATE UNIQUE INDEX IF NOT EXISTS uk_game_creature_species_id ON public.game_creature USING btree (species_id) WHERE default_form"},
	{name: "uk_game_creature_evolution_from_creature_id_to_creatur_38936b00", statement: "CREATE UNIQUE INDEX IF NOT EXISTS uk_game_creature_evolution_from_creature_id_to_creatur_38936b00 ON public.game_creature_evolution USING btree (from_creature_id, to_creature_id, condition_text)"},
	{name: "idx_game_creature_evolution_from_creature_id", statement: "CREATE INDEX IF NOT EXISTS idx_game_creature_evolution_from_creature_id ON public.game_creature_evolution USING btree (from_creature_id)"},
	{name: "idx_game_creature_evolution_to_creature_id", statement: "CREATE INDEX IF NOT EXISTS idx_game_creature_evolution_to_creature_id ON public.game_creature_evolution USING btree (to_creature_id)"},
	{name: "uk_game_creature_form_code", statement: "CREATE UNIQUE INDEX IF NOT EXISTS uk_game_creature_form_code ON public.game_creature_form USING btree (code)"},
	{name: "uk_game_creature_form_creature_id", statement: "CREATE UNIQUE INDEX IF NOT EXISTS uk_game_creature_form_creature_id ON public.game_creature_form USING btree (creature_id) WHERE default_form"},
	{name: "uk_game_creature_held_item_creature_id_item_id", statement: "CREATE UNIQUE INDEX IF NOT EXISTS uk_game_creature_held_item_creature_id_item_id ON public.game_creature_held_item USING btree (creature_id, item_id)"},
	{name: "uk_game_creature_skill_learn_creature_id_skill_id_lear_5e1716c5", statement: "CREATE UNIQUE INDEX IF NOT EXISTS uk_game_creature_skill_learn_creature_id_skill_id_lear_5e1716c5 ON public.game_creature_skill_learn USING btree (creature_id, skill_id, learn_method_id, level_learned_at)"},
	{name: "idx_game_creature_skill_learn_creature_id", statement: "CREATE INDEX IF NOT EXISTS idx_game_creature_skill_learn_creature_id ON public.game_creature_skill_learn USING btree (creature_id)"},
	{name: "idx_game_creature_skill_learn_skill_id", statement: "CREATE INDEX IF NOT EXISTS idx_game_creature_skill_learn_skill_id ON public.game_creature_skill_learn USING btree (skill_id)"},
	{name: "uk_game_creature_skin_creature_id_code", statement: "CREATE UNIQUE INDEX IF NOT EXISTS uk_game_creature_skin_creature_id_code ON public.game_creature_skin USING btree (creature_id, code)"},
	{name: "uk_game_creature_stat_creature_id_stat_id", statement: "CREATE UNIQUE INDEX IF NOT EXISTS uk_game_creature_stat_creature_id_stat_id ON public.game_creature_stat USING btree (creature_id, stat_id)"},
	{name: "uk_game_currency_code", statement: "CREATE UNIQUE INDEX IF NOT EXISTS uk_game_currency_code ON public.game_currency USING btree (code)"},
	{name: "uk_game_egg_group_code", statement: "CREATE UNIQUE INDEX IF NOT EXISTS uk_game_egg_group_code ON public.game_egg_group USING btree (code)"},
	{name: "uk_game_element_code", statement: "CREATE UNIQUE INDEX IF NOT EXISTS uk_game_element_code ON public.game_element USING btree (code)"},
	{name: "uk_game_element_effectiveness_attack_element_id_defens_38f8bf6a", statement: "CREATE UNIQUE INDEX IF NOT EXISTS uk_game_element_effectiveness_attack_element_id_defens_38f8bf6a ON public.game_element_effectiveness USING btree (attack_element_id, defense_element_id)"},
	{name: "uk_game_gender_code", statement: "CREATE UNIQUE INDEX IF NOT EXISTS uk_game_gender_code ON public.game_gender USING btree (code)"},
	{name: "uk_game_growth_rate_code", statement: "CREATE UNIQUE INDEX IF NOT EXISTS uk_game_growth_rate_code ON public.game_growth_rate USING btree (code)"},
	{name: "uk_game_habitat_code", statement: "CREATE UNIQUE INDEX IF NOT EXISTS uk_game_habitat_code ON public.game_habitat USING btree (code)"},
	{name: "uk_game_item_catalog_category_code", statement: "CREATE UNIQUE INDEX IF NOT EXISTS uk_game_item_catalog_category_code ON public.game_item_catalog_category USING btree (code)"},
	{name: "uk_game_item_category_code", statement: "CREATE UNIQUE INDEX IF NOT EXISTS uk_game_item_category_code ON public.game_item_category USING btree (code)"},
	{name: "uk_game_item_code", statement: "CREATE UNIQUE INDEX IF NOT EXISTS uk_game_item_code ON public.game_item USING btree (code)"},
	{name: "uk_game_item_pocket_code", statement: "CREATE UNIQUE INDEX IF NOT EXISTS uk_game_item_pocket_code ON public.game_item_pocket USING btree (code)"},
	{name: "uk_game_item_attribute_code", statement: "CREATE UNIQUE INDEX IF NOT EXISTS uk_game_item_attribute_code ON public.game_item_attribute USING btree (code)"},
	{name: "uk_game_item_fling_effect_code", statement: "CREATE UNIQUE INDEX IF NOT EXISTS uk_game_item_fling_effect_code ON public.game_item_fling_effect USING btree (code)"},
	{name: "uk_game_nature_code", statement: "CREATE UNIQUE INDEX IF NOT EXISTS uk_game_nature_code ON public.game_nature USING btree (code)"},
	{name: "uk_game_skill_ailment_code", statement: "CREATE UNIQUE INDEX IF NOT EXISTS uk_game_skill_ailment_code ON public.game_skill_ailment USING btree (code)"},
	{name: "uk_game_skill_category_code", statement: "CREATE UNIQUE INDEX IF NOT EXISTS uk_game_skill_category_code ON public.game_skill_category USING btree (code)"},
	{name: "uk_game_skill_code", statement: "CREATE UNIQUE INDEX IF NOT EXISTS uk_game_skill_code ON public.game_skill USING btree (code)"},
	{name: "uk_game_skill_damage_class_code", statement: "CREATE UNIQUE INDEX IF NOT EXISTS uk_game_skill_damage_class_code ON public.game_skill_damage_class USING btree (code)"},
	{name: "uk_game_skill_learn_method_code", statement: "CREATE UNIQUE INDEX IF NOT EXISTS uk_game_skill_learn_method_code ON public.game_skill_learn_method USING btree (code)"},
	{name: "uk_game_skill_stat_change_skill_id_stat_id", statement: "CREATE UNIQUE INDEX IF NOT EXISTS uk_game_skill_stat_change_skill_id_stat_id ON public.game_skill_stat_change USING btree (skill_id, stat_id)"},
	{name: "uk_game_skill_target_code", statement: "CREATE UNIQUE INDEX IF NOT EXISTS uk_game_skill_target_code ON public.game_skill_target USING btree (code)"},
	{name: "uk_game_species_code", statement: "CREATE UNIQUE INDEX IF NOT EXISTS uk_game_species_code ON public.game_species USING btree (code)"},
	{name: "uk_game_species_color_code", statement: "CREATE UNIQUE INDEX IF NOT EXISTS uk_game_species_color_code ON public.game_species_color USING btree (code)"},
	{name: "uk_game_species_national_dex_number", statement: "CREATE UNIQUE INDEX IF NOT EXISTS uk_game_species_national_dex_number ON public.game_species USING btree (national_dex_number)"},
	{name: "uk_game_species_shape_code", statement: "CREATE UNIQUE INDEX IF NOT EXISTS uk_game_species_shape_code ON public.game_species_shape USING btree (code)"},
	{name: "uk_game_stat_code", statement: "CREATE UNIQUE INDEX IF NOT EXISTS uk_game_stat_code ON public.game_stat USING btree (code)"},
	{name: "idx_battle_authoritative_summary_completed_at_battle_id", statement: "CREATE INDEX IF NOT EXISTS idx_battle_authoritative_summary_completed_at_battle_id ON public.battle_authoritative_summary USING btree (completed_at DESC, battle_id DESC)"},
	{name: "uk_battle_bot_strategy_code", statement: "CREATE UNIQUE INDEX IF NOT EXISTS uk_battle_bot_strategy_code ON public.battle_bot_strategy USING btree (code) WHERE enabled"},
	{name: "uk_battle_challenge_pending_pair", statement: "CREATE UNIQUE INDEX IF NOT EXISTS uk_battle_challenge_pending_pair ON public.battle_challenge USING btree (LEAST(challenger_player_character_id, target_player_character_id), GREATEST(challenger_player_character_id, target_player_character_id)) WHERE ((status)::text = 'pending'::text)"},
	{name: "idx_battle_challenge_pending_target", statement: "CREATE INDEX IF NOT EXISTS idx_battle_challenge_pending_target ON public.battle_challenge USING btree (target_account_id, target_player_character_id, expires_at, id) WHERE ((status)::text = 'pending'::text)"},
	{name: "idx_battle_outbox_created_at_id", statement: "CREATE INDEX IF NOT EXISTS idx_battle_outbox_created_at_id ON public.battle_outbox USING btree (created_at, id) WHERE (published_at IS NULL)"},
	{name: "idx_battle_status_created_at_id", statement: "CREATE INDEX IF NOT EXISTS idx_battle_status_created_at_id ON public.battle USING btree (status, created_at, id) WHERE status::text = ANY (ARRAY['created'::text, 'preview'::text, 'running'::text])"},
	{name: "uk_battle_challenge_id", statement: "CREATE UNIQUE INDEX IF NOT EXISTS uk_battle_challenge_id ON public.battle USING btree (challenge_id) WHERE challenge_id IS NOT NULL"},
	{name: "uk_battle_turn_record_battle_id_turn_number", statement: "CREATE UNIQUE INDEX IF NOT EXISTS uk_battle_turn_record_battle_id_turn_number ON public.battle_turn_record USING btree (battle_id, turn_number)"},
	{name: "idx_battle_turn_record_battle_id_turn_number", statement: "CREATE INDEX IF NOT EXISTS idx_battle_turn_record_battle_id_turn_number ON public.battle_turn_record USING btree (battle_id, turn_number)"},
	{name: "idx_battle_turn_submission_player_character_id_created_at", statement: "CREATE INDEX IF NOT EXISTS idx_battle_turn_submission_player_character_id_created_at ON public.battle_turn_submission USING btree (player_character_id, created_at DESC)"},
	{name: "idx_player_character_account_id_created_at_id", statement: "CREATE INDEX IF NOT EXISTS idx_player_character_account_id_created_at_id ON public.player_character USING btree (account_id, created_at, id)"},
	{name: "idx_player_character_creature_player_character_id", statement: "CREATE INDEX IF NOT EXISTS idx_player_character_creature_player_character_id ON public.player_character_creature USING btree (player_character_id)"},
	{name: "uk_player_character_creature_skill_player_character_cr_fb0049c0", statement: "CREATE UNIQUE INDEX IF NOT EXISTS uk_player_character_creature_skill_player_character_cr_fb0049c0 ON public.player_character_creature_skill USING btree (player_character_creature_id, skill_id)"},
	{name: "idx_player_character_currency_transaction_player_chara_3eaeb831", statement: "CREATE INDEX IF NOT EXISTS idx_player_character_currency_transaction_player_chara_3eaeb831 ON public.player_character_currency_transaction USING btree (player_character_id, created_at)"},
	{name: "idx_player_character_display_name_history_player_chara_94055fb5", statement: "CREATE INDEX IF NOT EXISTS idx_player_character_display_name_history_player_chara_94055fb5 ON public.player_character_display_name_history USING btree (player_character_id, claimed_at)"},
	{name: "idx_player_character_inventory_transaction_player_char_ab796b38", statement: "CREATE INDEX IF NOT EXISTS idx_player_character_inventory_transaction_player_char_ab796b38 ON public.player_character_inventory_transaction USING btree (player_character_id, created_at)"},
	{name: "uk_player_character_party_member_party_id_player_chara_697022d9", statement: "CREATE UNIQUE INDEX IF NOT EXISTS uk_player_character_party_member_party_id_player_chara_697022d9 ON public.player_character_party_member USING btree (party_id, player_character_creature_id)"},
	{name: "uk_player_character_sensitive_name_rule_normalized_match_type", statement: "CREATE UNIQUE INDEX IF NOT EXISTS uk_player_character_sensitive_name_rule_normalized_match_type ON public.player_character_sensitive_name_rule USING btree (normalized_term, match_type)"},
	{name: "idx_player_character_team_player_character_id_created_at_id", statement: "CREATE INDEX IF NOT EXISTS idx_player_character_team_player_character_id_created_at_id ON public.player_character_team USING btree (player_character_id, created_at, id)"},
	{name: "uk_player_character_team_member_skill_team_id_member_p_4c2eab51", statement: "CREATE UNIQUE INDEX IF NOT EXISTS uk_player_character_team_member_skill_team_id_member_p_4c2eab51 ON public.player_character_team_member_skill USING btree (team_id, member_position, skill_id)"},
	{name: "uk_player_character_team_player_character_id_name_key", statement: "CREATE UNIQUE INDEX IF NOT EXISTS uk_player_character_team_player_character_id_name_key ON public.player_character_team USING btree (player_character_id, name_key)"},
	{name: "uk_player_character_team_share_code_digest", statement: "CREATE UNIQUE INDEX IF NOT EXISTS uk_player_character_team_share_code_digest ON public.player_character_team_share USING btree (code_digest)"},
	{name: "idx_player_character_team_share_expires_at", statement: "CREATE INDEX IF NOT EXISTS idx_player_character_team_share_expires_at ON public.player_character_team_share USING btree (expires_at) WHERE (revoked_at IS NULL)"},
	{name: "idx_player_character_team_share_owner_player_character_5dc6b703", statement: "CREATE INDEX IF NOT EXISTS idx_player_character_team_share_owner_player_character_5dc6b703 ON public.player_character_team_share USING btree (owner_player_character_id, created_at, id)"},
	{name: "uk_rpg_dialogue_code", statement: "CREATE UNIQUE INDEX IF NOT EXISTS uk_rpg_dialogue_code ON public.rpg_dialogue USING btree (code)"},
	{name: "uk_rpg_encounter_entry_encounter_table_id_creature_id__5257f79f", statement: "CREATE UNIQUE INDEX IF NOT EXISTS uk_rpg_encounter_entry_encounter_table_id_creature_id__5257f79f ON public.rpg_encounter_entry USING btree (encounter_table_id, creature_id, form_id, minimum_level, maximum_level)"},
	{name: "uk_rpg_encounter_table_code", statement: "CREATE UNIQUE INDEX IF NOT EXISTS uk_rpg_encounter_table_code ON public.rpg_encounter_table USING btree (code)"},
	{name: "uk_rpg_location_code", statement: "CREATE UNIQUE INDEX IF NOT EXISTS uk_rpg_location_code ON public.rpg_location USING btree (code)"},
	{name: "uk_rpg_loot_entry_loot_table_id_item_id", statement: "CREATE UNIQUE INDEX IF NOT EXISTS uk_rpg_loot_entry_loot_table_id_item_id ON public.rpg_loot_entry USING btree (loot_table_id, item_id)"},
	{name: "uk_rpg_loot_table_code", statement: "CREATE UNIQUE INDEX IF NOT EXISTS uk_rpg_loot_table_code ON public.rpg_loot_table USING btree (code)"},
	{name: "uk_rpg_npc_code", statement: "CREATE UNIQUE INDEX IF NOT EXISTS uk_rpg_npc_code ON public.rpg_npc USING btree (code)"},
	{name: "uk_rpg_profession_code", statement: "CREATE UNIQUE INDEX IF NOT EXISTS uk_rpg_profession_code ON public.rpg_profession USING btree (code)"},
	{name: "uk_rpg_profession_skill_profession_id_code", statement: "CREATE UNIQUE INDEX IF NOT EXISTS uk_rpg_profession_skill_profession_id_code ON public.rpg_profession_skill USING btree (profession_id, code)"},
	{name: "uk_rpg_quest_code", statement: "CREATE UNIQUE INDEX IF NOT EXISTS uk_rpg_quest_code ON public.rpg_quest USING btree (code)"},
	{name: "uk_rpg_quest_objective_quest_id_position", statement: "CREATE UNIQUE INDEX IF NOT EXISTS uk_rpg_quest_objective_quest_id_position ON public.rpg_quest_objective USING btree (quest_id, \"position\")"},
	{name: "uk_rpg_recipe_code", statement: "CREATE UNIQUE INDEX IF NOT EXISTS uk_rpg_recipe_code ON public.rpg_recipe USING btree (code)"},
	{name: "uk_rpg_region_code", statement: "CREATE UNIQUE INDEX IF NOT EXISTS uk_rpg_region_code ON public.rpg_region USING btree (code)"},
	{name: "uk_rpg_shop_code", statement: "CREATE UNIQUE INDEX IF NOT EXISTS uk_rpg_shop_code ON public.rpg_shop USING btree (code)"},
	{name: "uk_account_username_key", statement: "CREATE UNIQUE INDEX IF NOT EXISTS uk_account_username_key ON public.account USING btree (username_key)"},
}

var schemaForeignKeyDefinitions = []schemaForeignKeyDefinition{
	{table: "active_player_character", name: "fk_active_player_character_account_id_id", definition: "FOREIGN KEY (account_id) REFERENCES account(id)"},
	{table: "active_player_character", name: "fk_active_player_character_player_character_id_id", definition: "FOREIGN KEY (player_character_id) REFERENCES player_character(id)"},
	{table: "active_player_character_team", name: "fk_active_player_character_team_player_character_id_id", definition: "FOREIGN KEY (player_character_id) REFERENCES player_character(id)"},
	{table: "active_player_character_team", name: "fk_active_player_character_team_team_id_id", definition: "FOREIGN KEY (team_id) REFERENCES player_character_team(id) ON DELETE CASCADE"},
	{table: "admin_audit_log", name: "fk_admin_audit_log_actor_account_id_id", definition: "FOREIGN KEY (actor_account_id) REFERENCES admin_account(id)"},
	{table: "admin_idempotency_record", name: "fk_admin_idempotency_record_actor_account_id_id", definition: "FOREIGN KEY (actor_account_id) REFERENCES admin_account(id) ON DELETE CASCADE"},
	{table: "admin_login_attempt", name: "fk_admin_login_attempt_account_id_id", definition: "FOREIGN KEY (account_id) REFERENCES admin_account(id) ON DELETE SET NULL"},
	{table: "administration_audit_log", name: "fk_administration_audit_log_actor_account_id_id", definition: "FOREIGN KEY (actor_account_id) REFERENCES account(id)"},
	{table: "administration_idempotency_record", name: "fk_administration_idempotency_record_actor_account_id_id", definition: "FOREIGN KEY (actor_account_id) REFERENCES account(id) ON DELETE CASCADE"},
	{table: "asset", name: "fk_asset_owner_account_id_id", definition: "FOREIGN KEY (owner_account_id) REFERENCES admin_account(id)"},
	{table: "game_creature", name: "fk_game_creature_inherits_from_creature_id_id", definition: "FOREIGN KEY (inherits_from_creature_id) REFERENCES game_creature(id)"},
	{table: "game_creature", name: "fk_game_creature_species_id_id", definition: "FOREIGN KEY (species_id) REFERENCES game_species(id)"},
	{table: "game_creature_ability", name: "fk_game_creature_ability_ability_id_id", definition: "FOREIGN KEY (ability_id) REFERENCES game_ability(id)"},
	{table: "game_creature_ability", name: "fk_game_creature_ability_creature_id_id", definition: "FOREIGN KEY (creature_id) REFERENCES game_creature(id)"},
	{table: "game_creature_evolution", name: "fk_game_creature_evolution_from_creature_id_id", definition: "FOREIGN KEY (from_creature_id) REFERENCES game_creature(id)"},
	{table: "game_creature_evolution", name: "fk_game_creature_evolution_required_skill_id_id", definition: "FOREIGN KEY (required_skill_id) REFERENCES game_skill(id)"},
	{table: "game_creature_evolution", name: "fk_game_creature_evolution_to_creature_id_id", definition: "FOREIGN KEY (to_creature_id) REFERENCES game_creature(id)"},
	{table: "game_creature_evolution", name: "fk_game_creature_evolution_trigger_item_id_id", definition: "FOREIGN KEY (trigger_item_id) REFERENCES game_item(id)"},
	{table: "game_creature_form", name: "fk_game_creature_form_creature_id_id", definition: "FOREIGN KEY (creature_id) REFERENCES game_creature(id)"},
	{table: "game_creature_form_element", name: "fk_game_creature_form_element_element_id_id", definition: "FOREIGN KEY (element_id) REFERENCES game_element(id)"},
	{table: "game_creature_form_element", name: "fk_game_creature_form_element_form_id_id", definition: "FOREIGN KEY (form_id) REFERENCES game_creature_form(id)"},
	{table: "game_creature_held_item", name: "fk_game_creature_held_item_creature_id_id", definition: "FOREIGN KEY (creature_id) REFERENCES game_creature(id)"},
	{table: "game_creature_held_item", name: "fk_game_creature_held_item_item_id_id", definition: "FOREIGN KEY (item_id) REFERENCES game_item(id)"},
	{table: "game_creature_skill_learn", name: "fk_game_creature_skill_learn_creature_id_id", definition: "FOREIGN KEY (creature_id) REFERENCES game_creature(id)"},
	{table: "game_creature_skill_learn", name: "fk_game_creature_skill_learn_learn_method_id_id", definition: "FOREIGN KEY (learn_method_id) REFERENCES game_skill_learn_method(id)"},
	{table: "game_creature_skill_learn", name: "fk_game_creature_skill_learn_skill_id_id", definition: "FOREIGN KEY (skill_id) REFERENCES game_skill(id)"},
	{table: "game_creature_skin", name: "fk_game_creature_skin_asset_id_id", definition: "FOREIGN KEY (asset_id) REFERENCES asset(id)"},
	{table: "game_creature_skin", name: "fk_game_creature_skin_creature_id_id", definition: "FOREIGN KEY (creature_id) REFERENCES game_creature(id)"},
	{table: "game_creature_stat", name: "fk_game_creature_stat_creature_id_id", definition: "FOREIGN KEY (creature_id) REFERENCES game_creature(id)"},
	{table: "game_creature_stat", name: "fk_game_creature_stat_stat_id_id", definition: "FOREIGN KEY (stat_id) REFERENCES game_stat(id)"},
	{table: "game_element_effectiveness", name: "fk_game_element_effectiveness_attack_element_id_id", definition: "FOREIGN KEY (attack_element_id) REFERENCES game_element(id)"},
	{table: "game_element_effectiveness", name: "fk_game_element_effectiveness_defense_element_id_id", definition: "FOREIGN KEY (defense_element_id) REFERENCES game_element(id)"},
	{table: "game_item", name: "fk_game_item_asset_id_id", definition: "FOREIGN KEY (asset_id) REFERENCES asset(id)"},
	{table: "game_item", name: "fk_game_item_category_id_id", definition: "FOREIGN KEY (category_id) REFERENCES game_item_category(id)"},
	{table: "game_item", name: "fk_game_item_fling_effect_id_id", definition: "FOREIGN KEY (fling_effect_id) REFERENCES game_item_fling_effect(id)"},
	{table: "game_item_category", name: "fk_game_item_category_pocket_id_id", definition: "FOREIGN KEY (pocket_id) REFERENCES game_item_pocket(id)"},
	{table: "game_item_attribute_binding", name: "fk_game_item_attribute_binding_item_id_id", definition: "FOREIGN KEY (item_id) REFERENCES game_item(id)"},
	{table: "game_item_attribute_binding", name: "fk_game_item_attribute_binding_attribute_id_id", definition: "FOREIGN KEY (attribute_id) REFERENCES game_item_attribute(id)"},
	{table: "game_item_status_rule", name: "fk_game_item_status_rule_item_id_id", definition: "FOREIGN KEY (item_id) REFERENCES game_item(id)"},
	{table: "game_item_damage_rule", name: "fk_game_item_damage_rule_item_id_id", definition: "FOREIGN KEY (item_id) REFERENCES game_item(id)"},
	{table: "game_item_damage_rule", name: "fk_game_item_damage_rule_element_boost_element_id_id", definition: "FOREIGN KEY (element_boost_element_id) REFERENCES game_element(id)"},
	{table: "game_item_damage_rule", name: "fk_game_item_damage_rule_consumable_boost_element_id_id", definition: "FOREIGN KEY (consumable_boost_element_id) REFERENCES game_element(id)"},
	{table: "game_item_damage_rule", name: "fk_game_item_damage_rule_reduction_element_id_id", definition: "FOREIGN KEY (reduction_element_id) REFERENCES game_element(id)"},
	{table: "game_item_stat_booster_ability", name: "fk_game_item_stat_booster_ability_item_id_id", definition: "FOREIGN KEY (item_id) REFERENCES game_item(id)"},
	{table: "game_item_stat_booster_ability", name: "fk_game_item_stat_booster_ability_ability_id_id", definition: "FOREIGN KEY (ability_id) REFERENCES game_ability(id)"},
	{table: "game_item_weather_rule", name: "fk_game_item_weather_rule_item_id_id", definition: "FOREIGN KEY (item_id) REFERENCES game_item(id)"},
	{table: "game_item_switch_rule", name: "fk_game_item_switch_rule_item_id_id", definition: "FOREIGN KEY (item_id) REFERENCES game_item(id)"},
	{table: "game_item_contact_rule", name: "fk_game_item_contact_rule_item_id_id", definition: "FOREIGN KEY (item_id) REFERENCES game_item(id)"},
	{table: "game_item_recovery_rule", name: "fk_game_item_recovery_rule_item_id_id", definition: "FOREIGN KEY (item_id) REFERENCES game_item(id)"},
	{table: "game_item_stat_rule", name: "fk_game_item_stat_rule_item_id_id", definition: "FOREIGN KEY (item_id) REFERENCES game_item(id)"},
	{table: "game_item_stat_rule", name: "fk_game_item_stat_rule_water_spa_element_id_id", definition: "FOREIGN KEY (water_spa_element_id) REFERENCES game_element(id)"},
	{table: "game_item_stat_rule", name: "fk_game_item_stat_rule_electric_atk_element_id_id", definition: "FOREIGN KEY (electric_atk_element_id) REFERENCES game_element(id)"},
	{table: "game_item_stat_rule", name: "fk_game_item_stat_rule_water_spd_element_id_id", definition: "FOREIGN KEY (water_spd_element_id) REFERENCES game_element(id)"},
	{table: "game_item_stat_rule", name: "fk_game_item_stat_rule_ice_atk_element_id_id", definition: "FOREIGN KEY (ice_atk_element_id) REFERENCES game_element(id)"},
	{table: "game_item_action_rule", name: "fk_game_item_action_rule_item_id_id", definition: "FOREIGN KEY (item_id) REFERENCES game_item(id)"},
	{table: "game_item_multi_hit_rule", name: "fk_game_item_multi_hit_rule_item_id_id", definition: "FOREIGN KEY (item_id) REFERENCES game_item(id)"},
	{table: "game_item_weight_rule", name: "fk_game_item_weight_rule_item_id_id", definition: "FOREIGN KEY (item_id) REFERENCES game_item(id)"},
	{table: "game_item_catalog_category", name: "fk_game_item_catalog_category_parent_id_id", definition: "FOREIGN KEY (parent_id) REFERENCES game_item_catalog_category(id)"},
	{table: "game_item_catalog_category_binding", name: "fk_game_item_catalog_category_binding_category_id_id", definition: "FOREIGN KEY (category_id) REFERENCES game_item_catalog_category(id) ON DELETE CASCADE"},
	{table: "game_item_catalog_category_binding", name: "fk_game_item_catalog_category_binding_item_id_id", definition: "FOREIGN KEY (item_id) REFERENCES game_item(id) ON DELETE CASCADE"},
	{table: "game_nature", name: "fk_game_nature_decreased_stat_id_id", definition: "FOREIGN KEY (decreased_stat_id) REFERENCES game_stat(id)"},
	{table: "game_nature", name: "fk_game_nature_increased_stat_id_id", definition: "FOREIGN KEY (increased_stat_id) REFERENCES game_stat(id)"},
	{table: "game_skill", name: "fk_game_skill_damage_class_id_id", definition: "FOREIGN KEY (damage_class_id) REFERENCES game_skill_damage_class(id)"},
	{table: "game_skill", name: "fk_game_skill_element_id_id", definition: "FOREIGN KEY (element_id) REFERENCES game_element(id)"},
	{table: "game_skill_stat_change", name: "fk_game_skill_stat_change_skill_id_id", definition: "FOREIGN KEY (skill_id) REFERENCES game_skill(id)"},
	{table: "game_skill_stat_change", name: "fk_game_skill_stat_change_stat_id_id", definition: "FOREIGN KEY (stat_id) REFERENCES game_stat(id)"},
	{table: "game_species", name: "fk_game_species_color_id_id", definition: "FOREIGN KEY (color_id) REFERENCES game_species_color(id)"},
	{table: "game_species", name: "fk_game_species_growth_rate_id_id", definition: "FOREIGN KEY (growth_rate_id) REFERENCES game_growth_rate(id)"},
	{table: "game_species", name: "fk_game_species_habitat_id_id", definition: "FOREIGN KEY (habitat_id) REFERENCES game_habitat(id)"},
	{table: "game_species", name: "fk_game_species_shape_id_id", definition: "FOREIGN KEY (shape_id) REFERENCES game_species_shape(id)"},
	{table: "game_species_egg_group", name: "fk_game_species_egg_group_egg_group_id_id", definition: "FOREIGN KEY (egg_group_id) REFERENCES game_egg_group(id)"},
	{table: "game_species_egg_group", name: "fk_game_species_egg_group_species_id_id", definition: "FOREIGN KEY (species_id) REFERENCES game_species(id)"},
	{table: "battle_participant_reservation", name: "fk_battle_participant_reservation_player_character_id_id", definition: "FOREIGN KEY (player_character_id) REFERENCES player_character(id)"},
	{table: "battle_runtime_lease", name: "fk_battle_runtime_lease_battle_id_id", definition: "FOREIGN KEY (battle_id) REFERENCES battle(id) ON DELETE CASCADE"},
	{table: "battle_authoritative_summary", name: "fk_battle_authoritative_summary_battle_id_id", definition: "FOREIGN KEY (battle_id) REFERENCES battle(id) ON DELETE RESTRICT"},
	{table: "player_character_equipment_loadout_state", name: "fk_player_character_equipment_loadout_state_id_id", definition: "FOREIGN KEY (id) REFERENCES player_character(id) ON DELETE RESTRICT"},
	{table: "battle_challenge", name: "fk_battle_challenge_battle_format_id_id", definition: "FOREIGN KEY (battle_format_id) REFERENCES game_battle_format(id)"},
	{table: "battle_challenge", name: "fk_battle_challenge_challenger_account_id_id", definition: "FOREIGN KEY (challenger_account_id) REFERENCES account(id)"},
	{table: "battle_challenge", name: "fk_battle_challenge_challenger_player_character_id_id", definition: "FOREIGN KEY (challenger_player_character_id) REFERENCES player_character(id)"},
	{table: "battle_challenge", name: "fk_battle_challenge_challenger_team_id_id", definition: "FOREIGN KEY (challenger_team_id) REFERENCES player_character_team(id)"},
	{table: "battle_challenge", name: "fk_battle_challenge_target_account_id_id", definition: "FOREIGN KEY (target_account_id) REFERENCES account(id)"},
	{table: "battle_challenge", name: "fk_battle_challenge_target_player_character_id_id", definition: "FOREIGN KEY (target_player_character_id) REFERENCES player_character(id)"},
	{table: "battle_disclosure_ledger", name: "fk_battle_disclosure_ledger_battle_id_id", definition: "FOREIGN KEY (battle_id) REFERENCES battle(id) ON DELETE CASCADE"},
	{table: "battle_outbox", name: "fk_battle_outbox_battle_id_id", definition: "FOREIGN KEY (battle_id) REFERENCES battle(id) ON DELETE CASCADE"},
	{table: "battle_participant", name: "fk_battle_participant_account_id_id", definition: "FOREIGN KEY (account_id) REFERENCES account(id)"},
	{table: "battle_participant", name: "fk_battle_participant_battle_id_id", definition: "FOREIGN KEY (battle_id) REFERENCES battle(id) ON DELETE CASCADE"},
	{table: "battle_participant", name: "fk_battle_participant_player_character_id_id", definition: "FOREIGN KEY (player_character_id) REFERENCES player_character(id)"},
	{table: "battle_participant", name: "fk_battle_participant_source_team_id_id", definition: "FOREIGN KEY (source_team_id) REFERENCES player_character_team(id)"},
	{table: "battle_preview_submission", name: "fk_battle_preview_submission_battle_id_id", definition: "FOREIGN KEY (battle_id) REFERENCES battle(id) ON DELETE CASCADE"},
	{table: "battle_turn_record", name: "fk_battle_turn_record_battle_id_id", definition: "FOREIGN KEY (battle_id) REFERENCES battle(id) ON DELETE CASCADE"},
	{table: "battle_turn_submission", name: "fk_battle_turn_submission_battle_id_side", definition: "FOREIGN KEY (battle_id, side) REFERENCES battle_participant(battle_id, side) ON DELETE CASCADE"},
	{table: "battle_turn_submission", name: "fk_battle_turn_submission_battle_id_state_version", definition: "FOREIGN KEY (battle_id, state_version) REFERENCES battle_turn_record(battle_id, state_version) ON DELETE CASCADE"},
	{table: "battle_turn_submission", name: "fk_battle_turn_submission_player_character_id_id", definition: "FOREIGN KEY (player_character_id) REFERENCES player_character(id)"},
	{table: "player_character", name: "fk_player_character_account_id_id", definition: "FOREIGN KEY (account_id) REFERENCES account(id)"},
	{table: "player_character_creature", name: "fk_player_character_creature_ability_id_id", definition: "FOREIGN KEY (ability_id) REFERENCES game_ability(id)"},
	{table: "player_character_creature", name: "fk_player_character_creature_captured_with_item_id_id", definition: "FOREIGN KEY (captured_with_item_id) REFERENCES game_item(id)"},
	{table: "player_character_creature", name: "fk_player_character_creature_creature_id_id", definition: "FOREIGN KEY (creature_id) REFERENCES game_creature(id)"},
	{table: "player_character_creature", name: "fk_player_character_creature_form_id_id", definition: "FOREIGN KEY (form_id) REFERENCES game_creature_form(id)"},
	{table: "player_character_creature", name: "fk_player_character_creature_gender_id_id", definition: "FOREIGN KEY (gender_id) REFERENCES game_gender(id)"},
	{table: "player_character_creature", name: "fk_player_character_creature_held_item_id_id", definition: "FOREIGN KEY (held_item_id) REFERENCES game_item(id)"},
	{table: "player_character_creature", name: "fk_player_character_creature_nature_id_id", definition: "FOREIGN KEY (nature_id) REFERENCES game_nature(id)"},
	{table: "player_character_creature", name: "fk_player_character_creature_origin_location_id_id", definition: "FOREIGN KEY (origin_location_id) REFERENCES rpg_location(id)"},
	{table: "player_character_creature", name: "fk_player_character_creature_player_character_id_id", definition: "FOREIGN KEY (player_character_id) REFERENCES player_character(id) ON DELETE CASCADE"},
	{table: "player_character_creature", name: "fk_player_character_creature_skin_id_id", definition: "FOREIGN KEY (skin_id) REFERENCES game_creature_skin(id)"},
	{table: "player_character_creature_skill", name: "fk_player_character_creature_skill_player_character_cr_0d97827f", definition: "FOREIGN KEY (player_character_creature_id) REFERENCES player_character_creature(id) ON DELETE CASCADE"},
	{table: "player_character_creature_skill", name: "fk_player_character_creature_skill_skill_id_id", definition: "FOREIGN KEY (skill_id) REFERENCES game_skill(id)"},
	{table: "player_character_creature_stat", name: "fk_player_character_creature_stat_player_character_cre_6a81df8e", definition: "FOREIGN KEY (player_character_creature_id) REFERENCES player_character_creature(id) ON DELETE CASCADE"},
	{table: "player_character_creature_stat", name: "fk_player_character_creature_stat_stat_id_id", definition: "FOREIGN KEY (stat_id) REFERENCES game_stat(id)"},
	{table: "player_character_currency_transaction", name: "fk_player_character_currency_transaction_currency_id_id", definition: "FOREIGN KEY (currency_id) REFERENCES game_currency(id)"},
	{table: "player_character_currency_transaction", name: "fk_player_character_currency_transaction_player_character_id_id", definition: "FOREIGN KEY (player_character_id) REFERENCES player_character(id) ON DELETE CASCADE"},
	{table: "player_character_display_name_history", name: "fk_player_character_display_name_history_player_character_id_id", definition: "FOREIGN KEY (player_character_id) REFERENCES player_character(id)"},
	{table: "player_character_inventory_item", name: "fk_player_character_inventory_item_item_id_id", definition: "FOREIGN KEY (item_id) REFERENCES game_item(id)"},
	{table: "player_character_inventory_item", name: "fk_player_character_inventory_item_player_character_id_id", definition: "FOREIGN KEY (player_character_id) REFERENCES player_character(id) ON DELETE CASCADE"},
	{table: "player_character_inventory_transaction", name: "fk_player_character_inventory_transaction_item_id_id", definition: "FOREIGN KEY (item_id) REFERENCES game_item(id)"},
	{table: "player_character_inventory_transaction", name: "fk_player_character_inventory_transaction_player_chara_2adebd14", definition: "FOREIGN KEY (player_character_id) REFERENCES player_character(id) ON DELETE CASCADE"},
	{table: "player_character_party_member", name: "fk_player_character_party_member_player_character_crea_53a3f01c", definition: "FOREIGN KEY (player_character_creature_id) REFERENCES player_character_creature(id) ON DELETE CASCADE"},
	{table: "player_character_profession", name: "fk_player_character_profession_player_character_id_id", definition: "FOREIGN KEY (player_character_id) REFERENCES player_character(id) ON DELETE CASCADE"},
	{table: "player_character_profession", name: "fk_player_character_profession_profession_id_id", definition: "FOREIGN KEY (profession_id) REFERENCES rpg_profession(id)"},
	{table: "player_character_profession_skill", name: "fk_player_character_profession_skill_player_character__f52b2e54", definition: "FOREIGN KEY (player_character_id, profession_id) REFERENCES player_character_profession(player_character_id, profession_id) ON DELETE CASCADE"},
	{table: "player_character_quest", name: "fk_player_character_quest_player_character_id_id", definition: "FOREIGN KEY (player_character_id) REFERENCES player_character(id) ON DELETE CASCADE"},
	{table: "player_character_quest", name: "fk_player_character_quest_quest_id_id", definition: "FOREIGN KEY (quest_id) REFERENCES rpg_quest(id)"},
	{table: "player_character_quest_objective", name: "fk_player_character_quest_objective_player_character_i_d886e8fe", definition: "FOREIGN KEY (player_character_id, quest_id) REFERENCES player_character_quest(player_character_id, quest_id) ON DELETE CASCADE"},
	{table: "player_character_team", name: "fk_player_character_team_player_character_id_id", definition: "FOREIGN KEY (player_character_id) REFERENCES player_character(id)"},
	{table: "player_character_team_member", name: "fk_player_character_team_member_nature_id_id", definition: "FOREIGN KEY (nature_id) REFERENCES game_nature(id)"},
	{table: "player_character_team_member", name: "fk_player_character_team_member_team_id_id", definition: "FOREIGN KEY (team_id) REFERENCES player_character_team(id) ON DELETE CASCADE"},
	{table: "player_character_team_member_skill", name: "fk_player_character_team_member_skill_team_id_member_p_96c52a3b", definition: "FOREIGN KEY (team_id, member_position) REFERENCES player_character_team_member(team_id, \"position\") ON DELETE CASCADE"},
	{table: "player_character_team_member_stat", name: "fk_player_character_team_member_stat_team_id_member_po_6eb75f33", definition: "FOREIGN KEY (team_id, member_position) REFERENCES player_character_team_member(team_id, \"position\") ON DELETE CASCADE"},
	{table: "player_character_team_share", name: "fk_player_character_team_share_owner_player_character_id_id", definition: "FOREIGN KEY (owner_player_character_id) REFERENCES player_character(id)"},
	{table: "player_character_wallet", name: "fk_player_character_wallet_currency_id_id", definition: "FOREIGN KEY (currency_id) REFERENCES game_currency(id)"},
	{table: "player_character_wallet", name: "fk_player_character_wallet_player_character_id_id", definition: "FOREIGN KEY (player_character_id) REFERENCES player_character(id) ON DELETE CASCADE"},
	{table: "player_character_world_state", name: "fk_player_character_world_state_player_character_id_id", definition: "FOREIGN KEY (player_character_id) REFERENCES player_character(id) ON DELETE CASCADE"},
	{table: "rpg_dialogue", name: "fk_rpg_dialogue_npc_id_id", definition: "FOREIGN KEY (npc_id) REFERENCES rpg_npc(id)"},
	{table: "rpg_dialogue_line", name: "fk_rpg_dialogue_line_dialogue_id_id", definition: "FOREIGN KEY (dialogue_id) REFERENCES rpg_dialogue(id) ON DELETE CASCADE"},
	{table: "rpg_encounter_entry", name: "fk_rpg_encounter_entry_creature_id_id", definition: "FOREIGN KEY (creature_id) REFERENCES game_creature(id)"},
	{table: "rpg_encounter_entry", name: "fk_rpg_encounter_entry_encounter_table_id_id", definition: "FOREIGN KEY (encounter_table_id) REFERENCES rpg_encounter_table(id) ON DELETE CASCADE"},
	{table: "rpg_encounter_entry", name: "fk_rpg_encounter_entry_form_id_id", definition: "FOREIGN KEY (form_id) REFERENCES game_creature_form(id)"},
	{table: "rpg_encounter_table", name: "fk_rpg_encounter_table_location_id_id", definition: "FOREIGN KEY (location_id) REFERENCES rpg_location(id)"},
	{table: "rpg_location", name: "fk_rpg_location_parent_id_id", definition: "FOREIGN KEY (parent_id) REFERENCES rpg_location(id)"},
	{table: "rpg_location", name: "fk_rpg_location_region_id_id", definition: "FOREIGN KEY (region_id) REFERENCES rpg_region(id)"},
	{table: "rpg_loot_entry", name: "fk_rpg_loot_entry_item_id_id", definition: "FOREIGN KEY (item_id) REFERENCES game_item(id)"},
	{table: "rpg_loot_entry", name: "fk_rpg_loot_entry_loot_table_id_id", definition: "FOREIGN KEY (loot_table_id) REFERENCES rpg_loot_table(id) ON DELETE CASCADE"},
	{table: "rpg_npc", name: "fk_rpg_npc_location_id_id", definition: "FOREIGN KEY (location_id) REFERENCES rpg_location(id)"},
	{table: "rpg_profession_skill", name: "fk_rpg_profession_skill_profession_id_id", definition: "FOREIGN KEY (profession_id) REFERENCES rpg_profession(id) ON DELETE CASCADE"},
	{table: "rpg_quest", name: "fk_rpg_quest_prerequisite_quest_id_id", definition: "FOREIGN KEY (prerequisite_quest_id) REFERENCES rpg_quest(id)"},
	{table: "rpg_quest", name: "fk_rpg_quest_start_npc_id_id", definition: "FOREIGN KEY (start_npc_id) REFERENCES rpg_npc(id)"},
	{table: "rpg_quest", name: "fk_rpg_quest_turn_in_npc_id_id", definition: "FOREIGN KEY (turn_in_npc_id) REFERENCES rpg_npc(id)"},
	{table: "rpg_quest_objective", name: "fk_rpg_quest_objective_quest_id_id", definition: "FOREIGN KEY (quest_id) REFERENCES rpg_quest(id) ON DELETE CASCADE"},
	{table: "rpg_quest_objective", name: "fk_rpg_quest_objective_target_creature_id_id", definition: "FOREIGN KEY (target_creature_id) REFERENCES game_creature(id)"},
	{table: "rpg_quest_objective", name: "fk_rpg_quest_objective_target_item_id_id", definition: "FOREIGN KEY (target_item_id) REFERENCES game_item(id)"},
	{table: "rpg_quest_objective", name: "fk_rpg_quest_objective_target_location_id_id", definition: "FOREIGN KEY (target_location_id) REFERENCES rpg_location(id)"},
	{table: "rpg_quest_objective", name: "fk_rpg_quest_objective_target_npc_id_id", definition: "FOREIGN KEY (target_npc_id) REFERENCES rpg_npc(id)"},
	{table: "rpg_quest_reward", name: "fk_rpg_quest_reward_creature_id_id", definition: "FOREIGN KEY (creature_id) REFERENCES game_creature(id)"},
	{table: "rpg_quest_reward", name: "fk_rpg_quest_reward_currency_id_id", definition: "FOREIGN KEY (currency_id) REFERENCES game_currency(id)"},
	{table: "rpg_quest_reward", name: "fk_rpg_quest_reward_item_id_id", definition: "FOREIGN KEY (item_id) REFERENCES game_item(id)"},
	{table: "rpg_quest_reward", name: "fk_rpg_quest_reward_quest_id_id", definition: "FOREIGN KEY (quest_id) REFERENCES rpg_quest(id) ON DELETE CASCADE"},
	{table: "rpg_recipe_ingredient", name: "fk_rpg_recipe_ingredient_item_id_id", definition: "FOREIGN KEY (item_id) REFERENCES game_item(id)"},
	{table: "rpg_recipe_ingredient", name: "fk_rpg_recipe_ingredient_recipe_id_id", definition: "FOREIGN KEY (recipe_id) REFERENCES rpg_recipe(id) ON DELETE CASCADE"},
	{table: "rpg_recipe_output", name: "fk_rpg_recipe_output_item_id_id", definition: "FOREIGN KEY (item_id) REFERENCES game_item(id)"},
	{table: "rpg_recipe_output", name: "fk_rpg_recipe_output_recipe_id_id", definition: "FOREIGN KEY (recipe_id) REFERENCES rpg_recipe(id) ON DELETE CASCADE"},
	{table: "rpg_shop", name: "fk_rpg_shop_location_id_id", definition: "FOREIGN KEY (location_id) REFERENCES rpg_location(id)"},
	{table: "rpg_shop", name: "fk_rpg_shop_npc_id_id", definition: "FOREIGN KEY (npc_id) REFERENCES rpg_npc(id)"},
	{table: "rpg_shop_item", name: "fk_rpg_shop_item_currency_id_id", definition: "FOREIGN KEY (currency_id) REFERENCES game_currency(id)"},
	{table: "rpg_shop_item", name: "fk_rpg_shop_item_item_id_id", definition: "FOREIGN KEY (item_id) REFERENCES game_item(id)"},
	{table: "rpg_shop_item", name: "fk_rpg_shop_item_shop_id_id", definition: "FOREIGN KEY (shop_id) REFERENCES rpg_shop(id) ON DELETE CASCADE"},
}
