spring:
  application:
    name: avalon
  datasource:
    url: jdbc:postgresql://localhost:5432/avalon
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: create-drop
  security:
    ignore-urls:
      - /token/sign-in
      - /user/sign-up
