package io.github.lishangbu.avalon.authorization.repository

import io.github.lishangbu.avalon.authorization.entity.AuthenticationLog
import jakarta.annotation.Resource
import org.junit.jupiter.api.Assertions.assertNotNull
import org.junit.jupiter.api.Assertions.assertTrue
import org.junit.jupiter.api.Test
import org.springframework.transaction.annotation.Transactional
import java.time.Instant

/**
 * 认证日志 Repository 测试
 *
 * 验证未手动赋值主键时，JPA @GeneratedValue 可正常生成 ID
 */
@Transactional(rollbackFor = [Exception::class])
class AuthenticationLogRepositoryTest : AbstractRepositoryTest() {
    @Resource
    private lateinit var authenticationLogRepository: AuthenticationLogRepository

    @Test
    fun testInsertAuthenticationLogWithAutoGeneratedId() {
        val saved =
            authenticationLogRepository.saveAndFlush(
                AuthenticationLog {
                    username = "unit-test-user"
                    clientId = "unit-test-client"
                    grantType = "password"
                    ip = "127.0.0.1"
                    userAgent = "JUnit"
                    success = true
                    occurredAt = Instant.now()
                },
            )

        assertNotNull(saved.id)
        assertTrue(saved.id > 0)
    }
}
