spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/avalon?currentSchema=public&sslmode=disable
jimmer:
  show-sql: true
  pretty-sql: true
  dialect: org.babyfish.jimmer.sql.dialect.PostgresDialect
oauth2:
  ignore-urls:
    - /actuator/**
    - /v3/api-docs
    - /auth/sms/code
    - /auth/email/code
    - /registry/machine
  jwt-private-key-location: classpath:rsa/private_key.pem
  jwt-public-key-location: classpath:rsa/public_key.pem
management:
  endpoints:
    web:
      exposure:
        include: health
