BEGIN;
insert into public.encounter_condition_value (id, internal_name, name, encounter_condition_id)
values (1, 'swarm-yes', 'During a swarm', 1),
       (2, 'swarm-no', 'Not during a swarm', 1),
       (3, 'time-morning', 'In the morning', 2),
       (4, 'time-day', 'During the day', 2),
       (5, 'time-night', 'At night', 2),
       (6, 'radar-on', 'Using PokéRadar', 3),
       (7, 'radar-off', 'Not using PokéRadar', 3),
       (8, 'slot2-none', 'No game in slot 2', 4),
       (9, 'slot2-ruby', 'Ruby in slot 2', 4),
       (10, 'slot2-sapphire', 'Sapphire in slot 2', 4),
       (11, 'slot2-emerald', 'Emerald in slot 2', 4),
       (12, 'slot2-firered', 'FireRed in slot 2', 4),
       (13, 'slot2-leafgreen', 'LeafGreen in slot 2', 4),
       (14, 'radio-off', 'Radio off', 5),
       (15, 'radio-hoenn', 'Hoenn radio', 5),
       (16, 'radio-sinnoh', 'Sinnoh radio', 5),
       (17, 'season-spring', 'During Spring', 6),
       (18, 'season-summer', 'During Summer', 6),
       (19, 'season-autumn', 'During Autumn', 6),
       (20, 'season-winter', 'During Winter', 6),
       (21, 'starter-bulbasaur', 'Bulbasaur as starter', 7),
       (22, 'starter-squirtle', 'Squirtle as starter', 7),
       (23, 'starter-charmander', 'Charmander as starter', 7),
       (24, 'starter-chespin', 'Chespin as starter', 7),
       (25, 'starter-fennekin', 'Fennekin as starter', 7),
       (26, 'starter-froakie', 'Froakie as starter', 7),
       (27, 'tv-option-blue', 'Chose ‘Blue’ on the TV news report', 8),
       (28, 'tv-option-red', 'Chose ‘Red’ on the TV news report', 8),
       (29, 'story-progress-awakened-beasts', 'Awakened the legendary beasts at Burned Tower', 9),
       (30, 'story-progress-beat-galactic-coronet', 'Visited Lake Verity after defeating Team Galactic at Mt. Coronet',
        9),
       (31, 'story-progress-oak-eterna-city', 'Talked to Professor Oak at Eterna City', 9),
       (32, 'story-progress-vermilion-copycat', 'Visited the Pokémon Fan Club with Copycat’s doll', 9),
       (33, 'story-progress-met-tornadus-thundurus', 'Met Tornadus or Thundurus in a cutscene', 9),
       (34, 'story-progress-beat-elite-four-round-two', 'Beat the Elite 4 for the second time', 9),
       (35, 'story-progress-hall-of-fame', 'Enter the Hall of Fame', 9),
       (36, 'story-progress-none', 'None', 9),
       (37, 'story-progress-national-dex', 'Acquired National Pokédex', 9),
       (38, 'other-none', 'None', 10),
       (39, 'other-snorlax-11-beat-league', 'Beat the Pokémon league after knocking out Snorlax at Route 11', 10),
       (40, 'other-virtual-console', 'Playing on the Virtual Console Release', 10),
       (41, 'story-progress-cure-eldritch-nightmares', 'Cure the nightmares of Eldritch’s Son', 9),
       (42, 'other-talk-to-cynthias-grandmother', 'Talk to Cynthia’s grandmother', 10),
       (43, 'item-none', 'No item requirement', 11),
       (44, 'item-adamant-orb', 'Have Adamant Orb in bag', 11),
       (45, 'item-lustrous-orb', 'Have Lustrous Orb in bag', 11),
       (46, 'item-helix-fossil', 'Have Helix Fossil in bag', 11),
       (47, 'item-dome-fossil', 'Have Dome Fossil in bag', 11),
       (48, 'item-old-amber', 'Have Old Amber in bag', 11),
       (49, 'item-root-fossil', 'Have Root Fossil in bag', 11),
       (50, 'item-claw-fossil', 'Have Claw Fossil in bag', 11),
       (51, 'story-progress-defeat-jupiter', 'Defeat Jupiter', 9),
       (52, 'story-progress-beat-team-galactic-iron-island', 'Defeat Team Galactic at Iron Island', 9),
       (53, 'other-correct-password', 'Input correct password', 10),
       (54, 'story-progress-zephyr-badge', 'Obtained Zephyr badge', 9),
       (55, 'story-progress-beat-red', 'Defeat Red', 9),
       (56, 'other-received-kanto-starter', 'Received a Kanto Starter', 10),
       (57, 'story-progress-receive-tm-from-claire', 'Received TM59 From Claire', 9),
       (58, 'other-regirock-regice-registeel-in-party', 'Have Regirock, Regice and Registeel in the party', 10),
       (59, 'weekday-sunday', 'Sunday', 12),
       (60, 'weekday-monday', 'Monday', 12),
       (61, 'weekday-tuesday', 'Tuesday', 12),
       (62, 'weekday-wednesday', 'Wednesday', 12),
       (63, 'weekday-thursday', 'Thursday', 12),
       (64, 'weekday-friday', 'Friday', 12),
       (65, 'weekday-saturday', 'Saturday', 12),
       (66, 'first-party-pokemon-high-friendship', 'The first Pokémon in the player’s party has a high friendship stat',
        13),
       (67, 'story-progress-defeat-mars', 'Beat Mars for the first time', 9),
       (68, 'item-odd-keystone', 'Have Odd Keystone in bag', 11),
       (69, 'other-talked-to-32-people-underground', 'Has talked to at least 32 people in the underground', 10),
       (70, 'story-progress-returned-machine-part', 'Returned Machine Part to Power Plant', 9),
       (71, 'other-event-arceus-in-party', 'Have an Event Arceus in the party', 10),
       (72, 'special-encounter-couldnt-capture-before',
        'This special Pokémon couldn’t be captured in previous encounters (either fainted or ran from battle)', 14),
       (73, 'item-ice-key', 'Have Ice Key in bag', 11),
       (74, 'item-iron-key', 'Have Iron Key in bag', 11),
       (75, 'story-progress-juniper-cave-of-being', 'Spoke to Professor Juniper in the Cave of Being', 9),
       (76, 'item-lunar-wing', 'Have Lunar Wing in bag', 11),
       (77, 'story-progress-quake-badge', 'Obtained Quake Badge', 9),
       (78, 'item-light-stone', 'Have Light Stone in bag', 11),
       (79, 'item-dark-stone', 'Have Dark Stone in bag', 11),
       (80, 'other-captured-reshiram-or-zekrom', 'Captured Reshiram or Zekrom previously', 10),
       (81, 'defeated-ghetsis', 'Defeated Ghetsis', 9),
       (82, 'other-found-11-times-roaming', 'Has been unsuccesfully battled 11 times before', 10),
       (83, 'time-minute-00-to-19', 'The current minute is between 00 and 19', 2),
       (84, 'time-minute-20-to-39', 'The current minute is between 20 and 39', 2),
       (85, 'time-minute-40-to-59', 'The current minute is between 40 and 59', 2),
       (86, 'time-04-00-to-19-59', 'The current time is between 04:00 and 19:59', 2),
       (87, 'time-20-00-to-21-59', 'The current time is between 20:00 and 21:59', 2),
       (88, 'time-21-00-to-03-59', 'The current time is between 22:00 and 03:59', 2),
       (89, 'item-tidal-bell', 'Have Tidal Bell in bag', 11),
       (90, 'item-clear-bell', 'Have Clear Bell in bag', 11),
       (91, 'story-progress-defeated-groudon-or-kyogre', 'Defeated or captured Groudon or Kyogre', 9),
       (92, 'other-uxie-mesprit-azelf-in-party', 'Have Uxie, Mesprit, and Azelf in the party', 10),
       (93, 'other-nicknamed-cold-item-regice-regirock-registeel3',
        'After capturing the three regis in the game, have a nicknamed Regice holding a cold-based item, plus Regirock and Registeel in the party',
        10),
       (94, 'other-dialga-or-palkia-in-party', 'Have Dialga or Palkia in the party', 10),
       (95, 'other-castform-in-party', 'Have Castform in party', 10),
       (96, 'other-level-100-pokemon-in-party', 'Have a Level 100 Pokémon in party', 10),
       (97, 'other-tornadus-thundurus-in-party', 'Have Tornadus and Thundurus in party', 10),
       (98, 'other-reshiram-zekrom-in-party', 'Have Reshiram and Zekrom in party', 10),
       (99, 'other-captured-all-ultra-beasts', 'Captured all Ultra Beasts', 10),
       (100, 'story-progress-finished-looker-sidequest', 'Finished Looker’s Sidequest', 9),
       (101, 'story-progress-beat-olivias-trial', 'After finishing Olivia’s trial', 9),
       (102, 'other-raikou-entei-in-party', 'Have Raikou and Entei in party', 10),
       (103, 'other-groudon-kyogre-in-party', 'Have Groudon and Kyogre in party', 10),
       (104, 'other-dialga-palkia-in-party', 'Have Dialga and Palkia in party', 10),
       (105, 'other-scan-qr-code', 'Scan a specific QR Code', 10),
       (106, 'other-caught-articuno', 'other-caught-articuno', 10),
       (107, 'other-caught-zapdos', 'other-caught-zapdos', 10),
       (108, 'other-caught-moltres', 'other-caught-moltres', 10);
COMMIT;