BEGIN;
insert into public.menu (id, component, disabled, enable_multi_tab, extra, icon, key, label, name, parent_id, path,
                         pinned, redirect, show, show_tab, sorting_order)
values (1, 'dashboard/index', false, false, null, 'icon-[mage--dashboard-chart]', 'dashboard', '仪表板', 'dashboard',
        null, 'dashboard', true, '', true, true, 0),
       (2, 'system', false, false, null, 'icon-[ph--diamonds-four]', 'system', '系统管理',
        'system', null, 'system', false, '', true, true, 0),
       (3, 'system/user/index', false, false, null, 'icon-[ph--user-list]', 'user', '用户管理',
        'user', 2, 'user', false, '', true, true, 0),
       (4, 'system/role/index', false, false, null, 'icon-[ph--person-light]', 'role', '角色管理',
        'role', 2, 'role', false, '', true, true, 0),
       (5, 'system/menu/index', false, false, null, 'icon-[ph--function-bold]', 'menu', '菜单管理',
        'menu', 2, 'menu', false, '', true, true, 0),
       (6, 'system/oauth-registered-client/index', false, false, null, 'icon-[ph--password]', 'oauth-registered-client', 'OAuth2客户端管理',
        'oauth-registered-client', 2, 'oauth-registered-client', false, '', true, true, 0),
       (7, 'dataset', false, false, null, 'icon-[ic--outline-dataset]', 'dataset', '数据集', 'dataset', null, 'dataset',
        false, '', true, true, 0),
       (8, 'dataset/type/index', false, false, null, 'icon-[game-icons--barbed-star]', 'type', '属性管理', 'type', 7,
        'type', false, '', true, true, 0),
       (9, 'dataset/type-damage-relation/index', false, false, null, 'icon-[game-icons--beveled-star]',
        'type-damage-relation', '属性克制管理', 'type-damage-relation', 7, 'type-damage-relation', false, '', true,
        true, 0),
       (10, 'dataset/berry-firmness/index', false, false, null, 'icon-[game-icons--diamond-hard]', 'berry-firmness',
        '树果硬度管理', 'berry-firmness', 7, 'berry-firmness', false, '', true, true, 0),
       (11, 'dataset/berry-flavor/index', false, false, null, 'icon-[game-icons--opened-food-can]', 'berry-flavor',
        '树果风味管理', 'berry-flavor', 7, 'berry-flavor', false, '', true, true, 0),
       (12, 'dataset/berry/index', false, false, null, 'icon-[game-icons--elderberry]', 'berry', '树果管理', 'berry', 7,
        'berry', false, '', true, true, 0),
       (13, 'dataset/stat/index', false, false, null, 'icon-[game-icons--holosphere]', 'stat', '能力管理',
        'stat', 7, 'stat', false, '', true, true, 0),
       (14, 'dataset/move-damage-class/index', false, false, null, 'icon-[game-icons--entangled-typhoon]', 'move-damage-class', '招式伤害类别管理',
        'move-damage-class', 7, 'move-damage-class', false, '', true, true, 0);
COMMIT;
