BEGIN;
insert into public.nature (id, internal_name, name, decreased_stat_id, hates_berry_flavor_id, increased_stat_id,
                           likes_berry_flavor_id)
values (1, 'hardy', '勤奋', null, null, null, null),
       (2, 'bold', '大胆', 2, 1, 3, 5),
       (3, 'modest', '内敛', 2, 1, 4, 2),
       (4, 'calm', '温和', 2, 1, 5, 4),
       (5, 'timid', '胆小', 2, 1, 6, 3),
       (6, 'lonely', '怕寂寞', 3, 5, 2, 1),
       (7, 'docile', '坦率', null, null, null, null),
       (8, 'mild', '慢吞吞', 3, 5, 4, 2),
       (9, 'gentle', '温顺', 3, 5, 5, 4),
       (10, 'hasty', '急躁', 3, 5, 6, 3),
       (11, 'adamant', '固执', 4, 2, 2, 1),
       (12, 'impish', '淘气', 4, 2, 3, 5),
       (13, 'bashful', '害羞', null, null, null, null),
       (14, 'careful', '慎重', 4, 2, 5, 4),
       (15, 'rash', '马虎', 5, 4, 4, 2),
       (16, 'jolly', '爽朗', 4, 2, 6, 3),
       (17, 'naughty', '顽皮', 5, 4, 2, 1),
       (18, 'lax', '乐天', 5, 4, 3, 5),
       (19, 'quirky', '浮躁', null, null, null, null),
       (20, 'naive', '天真', 5, 4, 6, 3),
       (21, 'brave', '勇敢', 6, 3, 2, 1),
       (22, 'relaxed', '悠闲', 6, 3, 3, 5),
       (23, 'quiet', '冷静', 6, 3, 4, 2),
       (24, 'sassy', '自大', 6, 3, 5, 4),
       (25, 'serious', '认真', null, null, null, null);
COMMIT;