spring:
  datasource:
    url: jdbc:h2:~/avalon.db;
    username: sa
    password:
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.H2Dialect
      ddl-auto: update
  main:
    banner-mode: off
  shell:
    interactive:
      enabled: true
logging:
  level:
    io:
      github:
        lishangbu:
          avalon: debug