package io.github.lishangbu.battlerules.service

import io.github.lishangbu.battlerules.dto.BattleRuleCoverageCheckResponse
import io.github.lishangbu.battlerules.dto.BattleRuleCoverageItemResponse
import io.github.lishangbu.battlerules.dto.BattleRuleCoverageMatrixRowResponse
import io.github.lishangbu.battlerules.dto.BattleRuleCoverageResponse
import io.github.lishangbu.battlerules.dto.BattleRuleCoverageSummaryResponse
import io.github.lishangbu.battlerules.dto.BattleRuleCoverageTargetSummaryResponse
import org.springframework.stereotype.Service

/**
 * 战斗规则实现覆盖报告服务。
 *
 * 该服务不读取数据库，因为覆盖状态来自代码、事件流和公开 fixture，而不是运营人员维护的资料。
 * 管理端使用它快速判断当前战斗引擎哪些规则已有公开对照、哪些只是部分接入、哪些仍在计划中。
 *
 * 清单中的 code 是稳定报告标识，不参与权限、路由或数据库主键。每次实现新规则并补充公开 fixture 后，
 * 应在这里同步把状态从 `PLANNED` 或 `PARTIAL` 推进到更准确的状态。
 */
@Service
class BattleRuleCoverageService {
	/**
	 * 读取当前战斗规则实现覆盖报告。
	 */
	fun getCoverage(): BattleRuleCoverageResponse {
		val items = coverageItems()
		val implementedCount = items.count { it.status == IMPLEMENTED }
		val partialCount = items.count { it.status == PARTIAL }
		val plannedCount = items.count { it.status == PLANNED }
		val fixtureCount = items.sumOf { it.fixtureNames.size }
		val implementationPercent = if (items.isEmpty()) {
			0
		} else {
			(implementedCount * 100) / items.size
		}
		return BattleRuleCoverageResponse(
			summary = BattleRuleCoverageSummaryResponse(
				totalCount = items.size,
				implementedCount = implementedCount,
				partialCount = partialCount,
				plannedCount = plannedCount,
				fixtureCount = fixtureCount,
				implementationPercent = implementationPercent,
			),
			targetSummary = BattleRuleCoverageTargetSummaryResponse(
				targetRuleCount = FINAL_TARGET_RULE_COUNT,
				coveredRuleCount = FINAL_COVERED_RULE_COUNT,
				remainingRuleCount = FINAL_TARGET_RULE_COUNT - FINAL_COVERED_RULE_COUNT,
				implementationPercent = (FINAL_COVERED_RULE_COUNT * 100) / FINAL_TARGET_RULE_COUNT,
				coverageItemCount = items.size,
				basis = FINAL_TARGET_BASIS,
			),
			matrix = coverageMatrix(items),
			checks = coverageChecks(items),
			items = items,
		)
	}

	private fun coverageMatrix(items: List<BattleRuleCoverageItemResponse>): List<BattleRuleCoverageMatrixRowResponse> =
		items.groupBy { it.category }
			.map { (category, categoryItems) ->
				val implementedCount = categoryItems.count { it.status == IMPLEMENTED }
				BattleRuleCoverageMatrixRowResponse(
					category = category,
					totalCount = categoryItems.size,
					implementedCount = implementedCount,
					partialCount = categoryItems.count { it.status == PARTIAL },
					plannedCount = categoryItems.count { it.status == PLANNED },
					fixtureCount = categoryItems.sumOf { it.fixtureNames.size },
					referenceCount = categoryItems.sumOf { it.referenceUrls.size },
					implementationPercent = if (categoryItems.isEmpty()) {
						0
					} else {
						(implementedCount * 100) / categoryItems.size
					},
				)
			}

	private fun coverageChecks(items: List<BattleRuleCoverageItemResponse>): List<BattleRuleCoverageCheckResponse> {
		val duplicateCodes = items.groupingBy { it.code }.eachCount().filterValues { it > 1 }.keys.sorted()
		val unknownStatuses = items.filterNot { it.status in RULE_STATUSES }.map { it.code }
		val blankCategoryCodes = items.filter { it.category.isBlank() }.map { it.code }
		val implementedWithoutFixtures = items.filter { it.status == IMPLEMENTED && it.fixtureNames.isEmpty() }.map { it.code }
		val implementedWithoutReferences = items.filter { it.status == IMPLEMENTED && it.referenceUrls.isEmpty() }.map { it.code }
		val goldenReplayCovered = items.any {
			it.code == GOLDEN_REPLAY_COVERAGE_CODE &&
				it.status == IMPLEMENTED &&
				it.fixtureNames.any { fixture -> fixture.contains("replay") }
		}
		return listOf(
			check(
				code = "target-count",
				name = "最终目标数量",
				passed = FINAL_TARGET_RULE_COUNT == REQUIRED_TARGET_RULE_COUNT &&
					FINAL_COVERED_RULE_COUNT == REQUIRED_TARGET_RULE_COUNT &&
					FINAL_COVERED_RULE_COUNT <= FINAL_TARGET_RULE_COUNT,
				success = "最终目标 $FINAL_TARGET_RULE_COUNT 条，已覆盖 $FINAL_COVERED_RULE_COUNT 条。",
				failure = "最终目标或已覆盖数量偏离 $REQUIRED_TARGET_RULE_COUNT 条。",
			),
			check(
				code = "unique-code",
				name = "规则 code 唯一",
				passed = duplicateCodes.isEmpty(),
				success = "所有覆盖项 code 均唯一。",
				failure = "存在重复 code: ${duplicateCodes.joinToString()}。",
			),
			check(
				code = "known-status",
				name = "状态值合法",
				passed = unknownStatuses.isEmpty(),
				success = "所有状态值均在 ${RULE_STATUSES.joinToString()} 内。",
				failure = "存在未知状态的规则项: ${unknownStatuses.joinToString()}。",
			),
			check(
				code = "category-filled",
				name = "分类已填写",
				passed = blankCategoryCodes.isEmpty(),
				success = "所有规则项均已填写分类。",
				failure = "存在未填写分类的规则项: ${blankCategoryCodes.joinToString()}。",
			),
			check(
				code = "implemented-fixtures",
				name = "已实现项有 fixture",
				passed = implementedWithoutFixtures.isEmpty(),
				success = "所有已实现规则项均绑定至少一个公开对照 fixture。",
				failure = "已实现但缺少 fixture 的规则项: ${implementedWithoutFixtures.joinToString()}。",
			),
			check(
				code = "implemented-references",
				name = "已实现项有来源",
				passed = implementedWithoutReferences.isEmpty(),
				success = "所有已实现规则项均记录至少一个公开来源。",
				failure = "已实现但缺少公开来源的规则项: ${implementedWithoutReferences.joinToString()}。",
			),
			check(
				code = "golden-replay",
				name = "Golden Replay 对照",
				passed = goldenReplayCovered,
				success = "严格 replay 已纳入覆盖报告，并绑定公开对照 fixture。",
				failure = "严格 replay 未纳入覆盖报告或缺少公开对照 fixture。",
			),
		)
	}

	private fun check(
		code: String,
		name: String,
		passed: Boolean,
		success: String,
		failure: String,
	): BattleRuleCoverageCheckResponse =
		BattleRuleCoverageCheckResponse(
			code = code,
			name = name,
			status = if (passed) CHECK_PASSED else CHECK_FAILED,
			message = if (passed) success else failure,
		)

	private fun coverageItems(): List<BattleRuleCoverageItemResponse> =
		listOf(
			item(
				code = "damage.standard-physical-special",
				name = "常规物理/特殊伤害公式",
				category = "伤害",
				status = IMPLEMENTED,
				fixtures = listOf(
					"level-50-neutral-same-element-physical-damage",
					"level-50-neutral-same-element-critical-hit-damage",
				),
				references = listOf(
					"https://github.com/smogon/damage-calc/blob/master/calc/src/mechanics/gen789.ts",
					"https://github.com/smogon/damage-calc/blob/master/calc/src/mechanics/util.ts",
				),
				note = "覆盖等级、威力、攻防、随机浮动、属性一致、属性克制和现代击中要害倍率。",
			),
			item(
				code = "damage.formula-boundaries",
				name = "普通伤害公式边界顺序",
				category = "伤害",
				status = IMPLEMENTED,
				fixtures = listOf(
					"level-fifty-neutral-same-element-physical-damage-keeps-base-formula",
					"non-matching-element-skips-same-element-bonus",
					"dual-type-effectiveness-multiplies-every-defending-element",
					"type-immunity-keeps-final-damage-at-zero-without-minimum-damage",
					"positive-non-immune-damage-is-floored-to-at-least-one",
					"damage-random-percent-is-applied-after-base-damage",
					"spread-target-modifier-participates-in-final-multiplier-chain",
					"side-damage-reduction-multiplier-participates-in-final-multiplier-chain",
					"critical-hit-applies-one-and-half-final-damage-multiplier",
					"burn-halves-physical-attack-before-base-damage",
					"positive-attack-stage-increases-physical-base-damage-before-final-multipliers",
					"positive-defense-stage-reduces-physical-base-damage-before-final-multipliers",
					"critical-hit-ignores-unfavorable-attack-and-favorable-defense-stages-in-formula",
					"critical-hit-keeps-burn-physical-attack-penalty",
					"special-damage-uses-special-attack-and-special-defense-stats",
					"sun-boosts-fire-damage-in-final-multiplier-chain",
					"rain-weakens-fire-damage-in-final-multiplier-chain",
					"grassy-terrain-boosts-grounded-grass-damage-in-formula",
					"grassy-terrain-weakens-tagged-ground-move-against-grounded-target",
					"power-stage-item-changes-base-damage-before-final-multipliers",
				),
				references = listOf(
					"https://github.com/smogon/damage-calc/blob/master/calc/src/mechanics/gen789.ts",
					"https://github.com/smogon/pokemon-showdown/blob/master/sim/battle-actions.ts",
					"https://bulbapedia.bulbagarden.net/wiki/Damage",
					"https://bulbapedia.bulbagarden.net/wiki/Weather",
					"https://bulbapedia.bulbagarden.net/wiki/Terrain",
				),
				note = "已覆盖普通伤害公式基础取整、属性一致命中/不命中、双属性克制连乘、属性免疫 0 伤害、非免疫最小 1 点、伤害随机、范围倍率、屏障倍率、要害倍率、灼伤、攻防阶级、要害忽略阶级但保留灼伤、特殊伤害分流、晴雨火属性修正、青草场地增伤和震动技能削弱，以及威力阶段道具先于基础伤害公式生效。",
			),
			item(
				code = "damage.double-spread",
				name = "双打范围伤害倍率",
				category = "伤害",
				status = IMPLEMENTED,
				fixtures = listOf("double-battle-spread-damage-uses-three-quarter-target-modifier"),
				references = listOf(
					"https://bulbapedia.bulbagarden.net/wiki/Damage",
					"https://github.com/smogon/pokemon-showdown/blob/master/sim/dex-moves.ts",
				),
				note = "多个实际目标时使用 0.75 目标倍率，只剩一个可战斗目标时保持 1.0。",
			),
			item(
				code = "damage.fixed-damage",
				name = "固定伤害技能",
				category = "伤害",
				status = IMPLEMENTED,
				fixtures = listOf(
					"fixed-damage-skills-use-fixed-amount-or-user-level",
					"fixed-damage-skill-respects-element-immunity",
				),
				references = listOf(
					"https://github.com/smogon/pokemon-showdown/blob/master/data/moves.ts",
				),
				note = "已覆盖固定数值伤害和按使用者等级造成固定伤害；这类技能不进入普通伤害公式、不消费要害或伤害浮动随机数，但仍受保护、命中、属性免疫、替身和伤害后流程影响。",
			),
			item(
				code = "damage.proportional-damage",
				name = "比例伤害技能",
				category = "伤害",
				status = IMPLEMENTED,
				fixtures = listOf(
					"proportional-damage-skill-halves-target-current-hp",
					"proportional-damage-skill-respects-element-immunity",
				),
				references = listOf(
					"https://github.com/smogon/pokemon-showdown/blob/master/data/moves.ts",
				),
				note = "已覆盖按目标当前 HP 的 1/2 向下取整且至少 1 点的直接伤害；该规则不进入普通伤害公式，但仍受保护、命中、属性免疫、替身和伤害后流程影响。",
			),
			item(
				code = "damage.hp-derived-damage",
				name = "HP 派生直接伤害技能",
				category = "伤害",
				status = IMPLEMENTED,
				fixtures = listOf(
					"hp-difference-damage-skill-reduces-target-to-user-current-hp",
					"hp-difference-damage-skill-fails-when-target-not-above-user",
					"user-current-hp-sacrifice-damage-skill-faints-user",
				),
				references = listOf(
					"https://github.com/smogon/pokemon-showdown/blob/master/data/moves.ts",
				),
				note = "已覆盖按目标与使用者当前 HP 差值造成直接伤害、差值不为正时失败，以及按使用者当前 HP 造成伤害并让使用者倒下；这些规则不进入普通伤害公式。",
			),
			item(
				code = "damage.critical-hit-flow",
				name = "击中要害流程",
				category = "伤害",
				status = IMPLEMENTED,
				fixtures = listOf(
					"stage-one-critical-hit-uses-one-eighth-chance",
					"stage-two-critical-hit-uses-one-half-chance",
					"stage-three-critical-hit-is-guaranteed-without-critical-random-consumption",
					"critical-hit-ignores-unfavorable-attack-and-favorable-defense-stages",
					"critical-hit-ignores-side-damage-reduction",
				),
				references = listOf(
					"https://github.com/smogon/pokemon-showdown/blob/master/sim/battle-actions.ts",
					"https://github.com/smogon/damage-calc/blob/master/calc/src/mechanics/gen789.ts",
					"https://wiki.52poke.com/wiki/击中要害",
				),
				note = "已覆盖 +1 要害等级 1/8、+2 要害等级 1/2、+3 及以上必定要害且不消费要害随机数、要害忽略攻击方不利和防守方有利能力阶级，以及要害绕过一侧伤害减免屏障。",
			),
			item(
				code = "replay.deterministic-random-trace",
				name = "确定性随机与严格回放",
				category = "随机/回放",
				status = IMPLEMENTED,
				fixtures = listOf(
					"scripted-random-rejects-extra-consumption",
					"recording-random-preserves-bound-reason-and-value-sequence",
					"strict-replay-reproduces-event-fragment-and-final-state",
					"strict-replay-rejects-tampered-random-trace",
				),
				references = listOf(
					"https://github.com/smogon/pokemon-showdown/blob/master/sim/battle.ts",
					"https://github.com/smogon/pokemon-showdown/blob/master/sim/battle-actions.ts",
					"https://github.com/smogon/pokemon-showdown/blob/master/sim/battle-queue.ts",
				),
				note = "已覆盖固定随机脚本拒绝额外消费、随机 trace 保存上界/原因/值、严格 replay 复算事件片段和最终状态，以及随机 trace 被篡改时立即失败。",
			),
			item(
				code = "field.side-damage-reduction",
				name = "一侧防守屏障伤害减免",
				category = "场上效果",
				status = IMPLEMENTED,
				fixtures = listOf(
					"double-battle-side-screen-uses-two-thirds-damage-modifier",
					"screen-extending-item-makes-side-damage-reduction-last-eight-turns",
				),
				references = listOf(
					"https://bulbapedia.bulbagarden.net/wiki/Reflect_(move)",
					"https://bulbapedia.bulbagarden.net/wiki/Light_Screen_(move)",
					"https://github.com/smogon/pokemon-showdown/blob/master/data/conditions.ts",
					"https://github.com/smogon/pokemon-showdown/blob/master/data/items.ts",
					"https://bulbapedia.bulbagarden.net/wiki/Light_Clay",
				),
				note = "已覆盖物理/特殊/全伤害屏障、单打 0.5、双打目标侧多人 2/3、击中要害忽略屏障、极光类屏障的天气前置条件，以及屏障延长道具把普通持续回合改为 8。",
			),
			item(
				code = "field.side-speed-modifier",
				name = "一侧速度结算修正",
				category = "场上效果",
				status = IMPLEMENTED,
				fixtures = listOf("tailwind-doubles-user-side-speed-for-later-action-order"),
				references = listOf(
					"https://github.com/smogon/pokemon-showdown/blob/master/data/conditions.ts",
					"https://bulbapedia.bulbagarden.net/wiki/Tailwind_(move)",
				),
				note = "已覆盖顺风在使用者一侧建立 2 倍速度结算修正，效果从后续行动排序开始生效，并按回合末统一递减。",
			),
			item(
				code = "field.speed-order",
				name = "全场速度顺序效果",
				category = "场上效果",
				status = IMPLEMENTED,
				fixtures = listOf(
					"trick-room-reverses-speed-order-inside-same-priority-bracket",
					"trick-room-used-while-active-ends-the-field-speed-order-effect",
				),
				references = listOf(
					"https://github.com/smogon/pokemon-showdown/blob/master/data/moves.ts",
					"https://bulbapedia.bulbagarden.net/wiki/Trick_Room_(move)",
				),
				note = "已覆盖戏法空间建立全场低速先动规则、同优先度内反转速度比较、再次使用解除效果，以及持续回合自然结束。",
			),
			item(
				code = "field.side-entry-hazard",
				name = "一侧入场陷阱",
				category = "场上效果",
				status = IMPLEMENTED,
				fixtures = listOf(
					"spikes-establishes-target-side-and-stacks-to-three-layers",
					"stealth-rock-damage-uses-rock-effectiveness-after-switch",
					"spikes-third-layer-damages-grounded-switch-in-only",
					"toxic-spikes-two-layers-badly-poisons-and-poison-element-absorbs",
					"sticky-web-lowers-grounded-switch-in-speed-stage",
				),
				references = listOf(
					"https://github.com/smogon/pokemon-showdown/blob/master/data/moves.ts",
					"https://bulbapedia.bulbagarden.net/wiki/Stealth_Rock_(move)",
					"https://bulbapedia.bulbagarden.net/wiki/Spikes_(move)",
					"https://bulbapedia.bulbagarden.net/wiki/Toxic_Spikes_(move)",
					"https://bulbapedia.bulbagarden.net/wiki/Sticky_Web_(move)",
				),
				note = "已覆盖目标侧建立、撒菱三层上限、隐形岩按岩属性相性扣血、撒菱只影响接地换入成员、毒菱中毒/剧毒与毒属性吸收，以及黏黏网降低接地换入成员速度阶级。",
			),
			item(
				code = "turn.target-slot-switch",
				name = "替换后的目标槽位重定向",
				category = "回合流程",
				status = IMPLEMENTED,
				fixtures = listOf("single-target-move-follows-replacement-slot"),
				references = listOf(
					"https://github.com/smogon/pokemon-showdown/blob/master/sim/battle-actions.ts",
					"https://github.com/smogon/pokemon-showdown/blob/master/sim/battle-queue.ts",
				),
				note = "主动替换先于普通技能结算，单体技能会命中同一槽位的新上场成员。",
			),
			item(
				code = "target.scope-resolution",
				name = "双打目标范围解析",
				category = "目标选择",
				status = IMPLEMENTED,
				fixtures = listOf(
					"selected-target-skill-hits-only-chosen-target-in-double-battle",
					"all-adjacent-opponents-skill-hits-both-opponents-and-skips-ally",
					"all-adjacent-participants-skill-hits-ally-and-opponents-but-excludes-user",
					"spread-skill-skips-fainted-opponent-and-keeps-full-target-multiplier",
					"spread-skill-recalculates-opponents-after-voluntary-switch",
					"all-adjacent-participants-skill-skips-fainted-ally",
				),
				references = listOf(
					"https://github.com/smogon/pokemon-showdown/blob/master/sim/battle-actions.ts",
					"https://github.com/smogon/pokemon-showdown/blob/master/sim/battle-queue.ts",
					"https://github.com/smogon/pokemon-showdown/blob/master/data/moves.ts",
				),
				note = "已覆盖双打单体技能只命中选中目标、全体相邻对手跳过队友、全体相邻成员命中队友和对手但排除使用者、范围技能跳过倒下目标、主动替换后重新收集目标，以及范围目标数量影响目标倍率。",
			),
			item(
				code = "target.redirection-and-empty-scope",
				name = "目标槽位重定向和空目标范围",
				category = "目标选择",
				status = IMPLEMENTED,
				fixtures = listOf(
					"selected-target-follows-single-battle-replacement-slot",
					"selected-target-in-double-follows-replaced-selected-slot-only",
					"selected-target-fainted-current-slot-does-not-redirect-to-other-slot",
					"selected-target-with-no-capable-active-member-cancels-before-pp",
					"all-adjacent-opponents-with-no-capable-opponents-cancels-before-pp",
					"all-adjacent-participants-with-only-user-capable-cancels-before-pp",
					"all-adjacent-opponents-ignores-submitted-target-actor",
					"all-adjacent-participants-ignores-selected-target-and-includes-ally",
					"spread-target-multiplier-remains-when-one-target-protects",
					"spread-target-order-follows-current-active-slot-order-after-switch",
				),
				references = listOf(
					"https://github.com/smogon/pokemon-showdown/blob/master/sim/battle-actions.ts",
					"https://github.com/smogon/pokemon-showdown/blob/master/sim/battle-queue.ts",
					"https://github.com/smogon/pokemon-showdown/blob/master/data/moves.ts",
				),
				note = "已覆盖单打和双打单体目标槽位替换后重定向、当前槽位濒死时不跨槽位改打、目标为空时不消耗 PP、范围技能忽略提交目标重新收集目标、全体相邻成员排除使用者，以及保护目标不改变多目标范围倍率。",
			),
			item(
				code = "target.random-adjacent-opponent",
				name = "随机相邻对手目标",
				category = "目标选择",
				status = IMPLEMENTED,
				fixtures = listOf(
					"random-adjacent-opponent-target-chooses-scripted-capable-opponent",
					"random-adjacent-opponent-with-no-capable-opponent-cancels-before-pp-and-random",
				),
				references = listOf(
					"https://github.com/smogon/pokemon-showdown/blob/master/sim/battle-actions.ts",
					"https://github.com/smogon/pokemon-showdown/blob/master/data/moves.ts",
					"https://wiki.52poke.com/wiki/濒死",
				),
				note = "已覆盖随机相邻对手技能忽略提交目标、按当前可战斗对手候选消费可复盘随机数，以及候选为空时在技能使用前取消且不消耗 PP 或随机数。",
			),
			item(
				code = "format.max-turn-limit",
				name = "格式回合上限裁定",
				category = "格式裁定",
				status = IMPLEMENTED,
				fixtures = listOf("max-turn-limit-ends-battle-as-draw-after-end-turn-effects"),
				references = listOf("https://bulbapedia.bulbagarden.net/wiki/Battle#Turn"),
				note = "格式声明最大回合数时，引擎在完整回合末检查上限；没有其它胜负结果时以无胜方平局结束。",
			),
			item(
				code = "format.preparation-validation",
				name = "准备阶段队伍合法性校验",
				category = "格式裁定",
				status = IMPLEMENTED,
				fixtures = listOf(
					"level-cap-rejects-over-level-participant",
					"banned-creature-rule-rejects-restricted-creature",
					"banned-skill-rule-rejects-restricted-skill",
					"banned-ability-rule-rejects-restricted-ability",
					"banned-item-rule-rejects-restricted-held-item",
					"unique-creature-clause-rejects-duplicates-only-inside-one-side",
					"unique-item-clause-rejects-duplicate-held-items-only-inside-one-side",
				),
				references = listOf(
					"https://github.com/smogon/pokemon-showdown/blob/master/config/formats.ts",
					"https://wiki.52poke.com/wiki/规则",
				),
				note = "已覆盖等级上限、禁用成员种类、禁用技能、禁用特性、禁用道具、同方成员种类唯一和同方携带道具唯一；校验器返回稳定违规 code，不让非法队伍进入战斗状态机。",
			),
			item(
				code = "turn.protection",
				name = "保护和连续保护成功率",
				category = "回合流程",
				status = IMPLEMENTED,
				fixtures = listOf(
					"protect-move-blocks-ordinary-target-move",
					"consecutive-protection-second-use-one-third-success",
					"consecutive-protection-second-use-can-fail-and-leave-user-unprotected",
				),
				references = listOf(
					"https://github.com/smogon/pokemon-showdown/blob/master/data/moves.ts",
					"https://github.com/smogon/pokemon-showdown/blob/master/sim/battle-actions.ts",
				),
				note = "保护类技能建立本回合屏障，连续保护按 1/3、1/9 等概率递减；失败时仍消耗 PP，但不会阻挡同回合攻击。",
			),
			item(
				code = "turn.action-flow-boundaries",
				name = "行动流程边界取消",
				category = "回合流程",
				status = IMPLEMENTED,
				fixtures = listOf(
					"protection-bypass-skill-damages-protected-target",
					"protection-blocks-before-accuracy-random",
					"protection-bypass-still-performs-accuracy-check",
					"fainted-queued-actor-cannot-execute-later-action",
					"action-with-no-battle-capable-selected-target-consumes-no-pp",
				),
				references = listOf(
					"https://github.com/smogon/pokemon-showdown/blob/master/sim/battle-actions.ts",
					"https://github.com/smogon/pokemon-showdown/blob/master/sim/battle-queue.ts",
					"https://wiki.52poke.com/wiki/守住（招式）",
					"https://wiki.52poke.com/wiki/濒死",
				),
				note = "已覆盖不受保护影响的技能继续命中目标、保护阻挡发生在命中随机之前、保护绕过后仍执行命中判定、排队成员倒下后取消行动，以及没有可战斗目标时不产生技能使用事件也不消耗 PP。",
			),
			item(
				code = "turn.action-submission-validation",
				name = "行动提交合法性校验",
				category = "回合流程",
				status = IMPLEMENTED,
				fixtures = listOf(
					"duplicate-action-submission-reports-every-duplicated-actor-action",
					"skill-with-no-pp-is-rejected-before-engine-resolution",
					"choice-locked-participant-cannot-submit-a-different-skill",
				),
				references = listOf(
					"https://github.com/smogon/pokemon-showdown/blob/master/sim/battle-actions.ts",
					"https://github.com/smogon/pokemon-showdown/blob/master/sim/battle-queue.ts",
					"https://github.com/smogon/pokemon-showdown/blob/master/data/items.ts",
				),
				note = "已覆盖同一成员重复提交行动、技能 PP 耗尽和讲究类技能锁定在提交阶段被结构化拦截；命中、保护、状态阻止等运行时事实仍保留给引擎事件流处理。",
			),
			item(
				code = "turn.action-ordering",
				name = "行动排序优先度和速度",
				category = "回合流程",
				status = IMPLEMENTED,
				fixtures = listOf(
					"positive-priority-acts-before-faster-normal-priority-skill",
					"negative-priority-acts-after-slower-normal-priority-skill",
					"higher-speed-acts-first-inside-same-priority-bracket",
					"same-speed-tie-consumes-random-order-keys",
					"same-positive-priority-bracket-still-orders-by-speed",
					"choice-speed-item-changes-action-order",
					"paralysis-speed-drop-changes-action-order",
					"side-speed-modifier-changes-action-order",
					"field-speed-order-reversal-changes-same-priority-action-order",
					"status-priority-ability-changes-action-order-before-faster-opponent",
				),
				references = listOf(
					"https://github.com/smogon/pokemon-showdown/blob/master/sim/battle-queue.ts",
					"https://github.com/smogon/pokemon-showdown/blob/master/data/moves.ts",
					"https://github.com/smogon/pokemon-showdown/blob/master/data/items.ts",
					"https://github.com/smogon/pokemon-showdown/blob/master/data/conditions.ts",
					"https://github.com/smogon/pokemon-showdown/blob/master/data/abilities.ts",
				),
				note = "已覆盖正优先度、负优先度、同优先度速度比较、同速随机、同正优先度内速度比较、讲究速度道具、麻痹速度下降、一侧速度修正、全场速度顺序反转，以及变化技能优先度特性参与行动排序。",
			),
			item(
				code = "lifecycle.switch-faint-result",
				name = "战斗生命周期和替换流程",
				category = "生命周期",
				status = IMPLEMENTED,
				fixtures = listOf(
					"battle-start-event-records-format-and-side-order",
					"last-opponent-faint-ends-battle-with-winning-side",
					"active-faint-with-reserve-does-not-end-battle",
					"voluntary-switch-replaces-active-slot-before-skill-phase",
					"fainted-active-switch-is-marked-forced",
					"switch-out-clears-volatile-counters-and-stat-stages",
					"switch-out-keeps-major-status-hp-and-pp",
					"recharge-prevents-voluntary-switch",
					"charging-prevents-voluntary-switch",
					"locked-move-prevents-voluntary-switch",
				),
				references = listOf(
					"https://github.com/smogon/pokemon-showdown/blob/master/sim/battle.ts",
					"https://github.com/smogon/pokemon-showdown/blob/master/sim/battle-actions.ts",
					"https://github.com/smogon/pokemon-showdown/blob/master/sim/battle-queue.ts",
					"https://github.com/smogon/pokemon-showdown/blob/master/sim/pokemon.ts",
					"https://github.com/smogon/pokemon-showdown/blob/master/data/moves.ts",
				),
				note = "已覆盖战斗开始事件、最后成员濒死后的胜负裁定、有后备成员时不结束战斗、主动替换先于技能阶段、濒死成员强制补位替换、离场清理能力阶级和临时计数、离场保留主要异常/HP/PP，以及休整、蓄力和锁招阻止主动替换。",
			),
			item(
				code = "turn.accuracy-evasion-stage",
				name = "命中和闪避阶级",
				category = "命中",
				status = IMPLEMENTED,
				fixtures = listOf(
					"target-evasion-stage-lowers-effective-accuracy",
					"user-accuracy-stage-raises-effective-accuracy",
					"weather-accuracy-overrides-support-sure-hit-and-lowered-accuracy",
				),
				references = listOf(
					"https://bulbapedia.bulbagarden.net/wiki/Stat_modifier",
					"https://github.com/smogon/pokemon-showdown/blob/master/sim/battle-actions.ts",
					"https://github.com/smogon/pokemon-showdown/blob/master/data/moves.ts",
				),
				note = "已覆盖使用者命中阶级和目标闪避阶级参与有效命中计算，以及天气命中覆盖对必中和降命中的影响。",
			),
			item(
				code = "hit.defense-boundaries",
				name = "命中、防护、替身和免疫边界",
				category = "命中/防护",
				status = IMPLEMENTED,
				fixtures = listOf(
					"sure-hit-skill-skips-accuracy-random-and-proceeds-to-damage",
					"accuracy-roll-equal-to-modified-accuracy-still-hits",
					"accuracy-miss-skips-critical-hit-and-damage-random",
					"positive-accuracy-stage-can-make-seventy-five-accuracy-skill-sure-hit",
					"positive-evasion-stage-can-make-one-hundred-accuracy-skill-miss",
					"weather-sure-hit-override-skips-accuracy-random",
					"first-successful-protection-consumes-no-chance-random",
					"second-consecutive-protection-success-consumes-one-third-chance-random",
					"failed-consecutive-protection-leaves-user-unprotected-for-later-damage",
					"protection-blocks-ally-affected-skill-in-double-battle",
					"substitute-fails-at-exact-hp-cost-after-skill-use",
					"substitute-fails-when-user-already-has-substitute-after-skill-use",
					"substitute-blocks-opponent-stat-stage-drop",
					"substitute-allows-ally-stat-stage-effect",
					"substitute-does-not-block-user-self-healing-skill",
					"grass-target-blocks-powder-status-skill-before-duration-random",
					"sound-immunity-ability-blocks-sound-skill-before-damage-random",
					"type-immunity-blocks-fixed-damage-before-direct-damage",
				),
				references = listOf(
					"https://github.com/smogon/pokemon-showdown/blob/master/sim/battle-actions.ts",
					"https://github.com/smogon/pokemon-showdown/blob/master/data/moves.ts",
					"https://github.com/smogon/pokemon-showdown/blob/master/data/conditions.ts",
					"https://github.com/smogon/pokemon-showdown/blob/master/data/abilities.ts",
				),
				note = "已覆盖必中、命中等于阈值、未命中短路、命中/闪避阶级造成必中或未命中、天气必中、首次和连续保护、保护失败后的受击、同侧技能被保护阻挡、替身失败条件、替身阻止对手能力变化但允许同侧和自身效果、草属性粉末免疫、声音免疫特性，以及属性免疫阻止固定伤害。",
			),
			item(
				code = "status.residual-major",
				name = "灼伤、中毒和剧毒回合末伤害",
				category = "主要状态",
				status = IMPLEMENTED,
				fixtures = listOf("bad-poison-residual-damage-increases-each-active-turn"),
				references = listOf("https://bulbapedia.bulbagarden.net/wiki/Poison_(status_condition)"),
				note = "灼伤和普通中毒按固定比例扣血，剧毒递增计数并在离场时重置为 1。",
			),
			item(
				code = "status.burn-physical-damage",
				name = "灼伤物理伤害减半",
				category = "主要状态",
				status = IMPLEMENTED,
				fixtures = listOf("burn-halves-physical-attacking-stat-before-damage"),
				references = listOf(
					"https://bulbapedia.bulbagarden.net/wiki/Burn_(status_condition)",
					"https://github.com/smogon/pokemon-showdown/blob/master/data/conditions.ts",
				),
				note = "已覆盖灼伤成员使用物理技能时，攻击侧数值先减半再进入普通伤害公式；击中要害仍不会绕过灼伤减半。",
			),
			item(
				code = "status.sleep-electric-terrain",
				name = "睡眠持续和电气场地防睡眠",
				category = "主要状态",
				status = IMPLEMENTED,
				fixtures = listOf(
					"sleep-prevents-two-actions-from-scripted-duration",
					"electric-terrain-blocks-new-sleep",
				),
				references = listOf(
					"https://bulbapedia.bulbagarden.net/wiki/Sleep_(status_condition)",
					"https://bulbapedia.bulbagarden.net/wiki/Electric_Terrain_(move)",
				),
				note = "睡眠按 1..3 次阻止行动建模；电气场地只阻止当前上场且接地的成员新获得睡眠。",
			),
			item(
				code = "status.paralysis-speed-action",
				name = "麻痹速度和行动阻止",
				category = "主要状态",
				status = IMPLEMENTED,
				fixtures = listOf(
					"paralysis-prevents-action-without-pp-loss",
					"paralysis-allows-action-after-failed-block-roll",
				),
				references = listOf(
					"https://github.com/smogon/pokemon-showdown/blob/master/data/conditions.ts",
					"https://bulbapedia.bulbagarden.net/wiki/Paralysis_(status_condition)",
				),
				note = "麻痹按有效速度减半参与行动排序，并在每次行动前以 25% 概率阻止技能且不消耗 PP。",
			),
			item(
				code = "status.volatile-flinch-confusion",
				name = "畏缩和混乱临时状态",
				category = "临时状态",
				status = IMPLEMENTED,
				fixtures = listOf(
					"flinch-prevents-slower-target-before-move",
					"late-flinch-does-not-carry-to-next-turn",
					"confusion-self-damage-and-later-clear",
					"existing-confusion-blocks-new-confusion-without-refresh",
				),
				references = listOf(
					"https://github.com/smogon/pokemon-showdown/blob/master/data/conditions.ts",
					"https://github.com/smogon/pokemon-showdown/blob/master/sim/battle-actions.ts",
					"https://bulbapedia.bulbagarden.net/wiki/Confusion_(status_condition)",
				),
				note = "畏缩只阻止本回合未行动成员；混乱使用 2..5 内部计数、33% 自伤和 40 威力物理自伤公式，已有混乱不会被再次附加刷新持续时间。",
			),
			item(
				code = "status.heal-block",
				name = "回复封锁临时状态",
				category = "临时状态",
				status = IMPLEMENTED,
				fixtures = listOf(
					"status-skill-applies-heal-block-to-target",
					"heal-blocked-participant-cannot-use-self-healing-status-skill",
					"heal-blocked-participant-cannot-use-draining-damage-skill",
					"heal-block-suppresses-end-turn-held-item-healing",
					"heal-block-clears-when-end-turn-duration-reaches-zero",
				),
				references = listOf(
					"https://github.com/smogon/pokemon-showdown/blob/master/data/moves.ts",
					"https://github.com/smogon/pokemon-showdown/blob/master/data/conditions.ts",
					"https://wiki.52poke.com/wiki/回复封锁（招式）",
					"https://wiki.52poke.com/wiki/回复封锁（状态变化）",
				),
				note = "已覆盖回复封锁附加、主动回复技能失败、吸取回复技能失败、回合末道具回复被抑制，以及持续回合在回合末递减并自然解除。",
			),
			item(
				code = "status.taunt",
				name = "挑衅临时状态",
				category = "临时状态",
				status = IMPLEMENTED,
				fixtures = listOf(
					"status-skill-applies-taunt-to-target",
					"taunted-participant-cannot-use-status-skill",
					"taunted-participant-can-use-damaging-skill",
					"taunt-clears-when-end-turn-duration-reaches-zero",
					"existing-taunt-blocks-new-taunt-without-refreshing-duration",
				),
				references = listOf(
					"https://github.com/smogon/pokemon-showdown/blob/master/data/moves.ts",
					"https://github.com/smogon/pokemon-showdown/blob/master/data/conditions.ts",
					"https://wiki.52poke.com/wiki/挑衅（招式）",
					"https://wiki.52poke.com/wiki/挑衅（状态变化）",
				),
				note = "已覆盖挑衅附加、变化技能在 PP 消耗前失败、攻击分类技能继续结算、回合末递减解除，以及已有挑衅不会刷新持续时间。",
			),
			item(
				code = "status.disable",
				name = "定身法临时状态",
				category = "临时状态",
				status = IMPLEMENTED,
				fixtures = listOf(
					"status-skill-disables-target-last-used-skill",
					"disabled-skill-cannot-be-used",
					"disabled-participant-can-use-other-skill",
					"disable-clears-when-end-turn-duration-reaches-zero",
					"disable-fails-when-target-has-no-last-used-skill",
				),
				references = listOf(
					"https://github.com/smogon/pokemon-showdown/blob/master/data/moves.ts",
					"https://github.com/smogon/pokemon-showdown/blob/master/data/conditions.ts",
					"https://wiki.52poke.com/wiki/定身法（招式）",
				),
				note = "已覆盖定身法读取目标上一次使用技能、被禁用技能在 PP 消耗前失败、其它技能继续可用、回合末递减解除，以及没有可禁用技能时失败。",
			),
			item(
				code = "status.torment",
				name = "无理取闹临时状态",
				category = "临时状态",
				status = IMPLEMENTED,
				fixtures = listOf(
					"status-skill-applies-torment-to-target",
					"tormented-participant-cannot-use-same-skill-twice",
					"tormented-participant-can-use-different-skill",
					"torment-clears-when-participant-switches-out",
					"existing-torment-blocks-new-torment-without-refreshing-state",
				),
				references = listOf(
					"https://github.com/smogon/pokemon-showdown/blob/master/data/moves.ts",
					"https://github.com/smogon/pokemon-showdown/blob/master/data/conditions.ts",
					"https://wiki.52poke.com/wiki/无理取闹（招式）",
					"https://wiki.52poke.com/wiki/无理取闹（状态变化）",
				),
				note = "已覆盖无理取闹附加、连续使用同一技能在 PP 消耗前失败、改用不同技能后更新最近技能、离场清除，以及已有无理取闹不会重复附加。",
			),
			item(
				code = "status.binding",
				name = "束缚临时状态",
				category = "临时状态",
				status = IMPLEMENTED,
				fixtures = listOf(
					"binding-skill-traps-target-and-deals-end-turn-damage",
					"bound-participant-cannot-switch-voluntarily",
					"bound-participant-takes-end-turn-binding-damage",
					"binding-clears-when-end-turn-duration-reaches-zero",
					"binding-clears-when-source-switches-out",
				),
				references = listOf(
					"https://github.com/smogon/pokemon-showdown/blob/master/data/moves.ts",
					"https://github.com/smogon/pokemon-showdown/blob/master/data/conditions.ts",
					"https://wiki.52poke.com/wiki/绑紧（招式）",
					"https://wiki.52poke.com/wiki/束缚（状态变化）",
				),
				note = "已覆盖束缚类技能命中后附加目标临时状态、阻止目标主动替换、回合末最大 HP 1/8 间接伤害、持续回合归零解除，以及来源离场解除。",
			),
			item(
				code = "terrain.grassy-heal",
				name = "青草场地核心效果",
				category = "场地",
				status = IMPLEMENTED,
				fixtures = listOf(
					"grassy-terrain-heals-active-participants-at-end-turn",
					"grassy-terrain-heals-only-grounded-active-participants",
					"grassy-terrain-boosts-grounded-grass-damage",
					"grassy-terrain-weakens-tagged-ground-shaking-moves-against-grounded-targets",
				),
				references = listOf(
					"https://github.com/smogon/pokemon-showdown/blob/master/data/conditions.ts",
					"https://bulbapedia.bulbagarden.net/wiki/Grassy_Terrain_(move)",
				),
				note = "已覆盖接地成员回合末回复、接地使用者草属性伤害增强，以及地面震动类技能命中接地目标减半。",
			),
			item(
				code = "terrain.psychic-priority-block",
				name = "精神场地先制阻挡",
				category = "场地",
				status = IMPLEMENTED,
				fixtures = listOf(
					"psychic-terrain-blocks-priority-move-against-grounded-opponent",
					"psychic-terrain-does-not-block-priority-move-against-ungrounded-opponent",
					"psychic-terrain-does-not-block-priority-move-against-ally",
				),
				references = listOf(
					"https://github.com/smogon/pokemon-showdown/blob/master/data/conditions.ts",
					"https://bulbapedia.bulbagarden.net/wiki/Psychic_Terrain_(move)",
				),
				note = "精神场地阻止对手针对接地成员的先制技能，非接地目标和同侧目标不受影响。",
			),
			item(
				code = "ability.status-priority-boost",
				name = "特性提升变化技能先制度",
				category = "特性",
				status = IMPLEMENTED,
				fixtures = listOf(
					"status-priority-ability-moves-status-skill-before-faster-opponent",
					"dark-target-blocks-opponent-status-skill-boosted-by-status-priority-ability",
					"status-priority-ability-does-not-make-ally-dark-target-immune",
				),
				references = listOf(
					"https://github.com/smogon/pokemon-showdown/blob/master/data/abilities.ts",
					"https://bulbapedia.bulbagarden.net/wiki/Prankster_(Ability)",
				),
				note = "已覆盖变化技能获得额外优先度、对手恶属性目标免疫，以及同侧恶属性目标不触发免疫。",
			),
			item(
				code = "ability.priority-move-block",
				name = "特性阻止对手先制技能",
				category = "特性",
				status = IMPLEMENTED,
				fixtures = listOf(
					"priority-blocking-ability-blocks-opponent-priority-move-against-holder",
					"priority-blocking-ability-protects-active-ally-from-opponent-priority-move",
					"priority-blocking-ability-does-not-block-ally-priority-move",
				),
				references = listOf(
					"https://github.com/smogon/pokemon-showdown/blob/master/data/abilities.ts",
					"https://bulbapedia.bulbagarden.net/wiki/Queenly_Majesty_(Ability)",
					"https://bulbapedia.bulbagarden.net/wiki/Dazzling_(Ability)",
					"https://bulbapedia.bulbagarden.net/wiki/Armor_Tail_(Ability)",
				),
				note = "已覆盖目标自身特性和同侧伙伴特性阻止对手先制技能；同侧成员主动使用先制技能不受阻挡。",
			),
			item(
				code = "ability.element-absorb-heal",
				name = "特性吸收指定属性技能并回复",
				category = "特性",
				status = IMPLEMENTED,
				fixtures = listOf(
					"element-absorb-ability-heals-and-blocks-matching-damage",
					"element-absorb-ability-at-full-hp-blocks-without-overhealing",
					"element-absorb-ability-blocks-matching-status-skill",
				),
				references = listOf(
					"https://github.com/smogon/pokemon-showdown/blob/master/data/abilities.ts",
					"https://bulbapedia.bulbagarden.net/wiki/Volt_Absorb_(Ability)",
					"https://bulbapedia.bulbagarden.net/wiki/Water_Absorb_(Ability)",
					"https://bulbapedia.bulbagarden.net/wiki/Earth_Eater_(Ability)",
				),
				note = "已覆盖匹配属性技能命中目标后被特性吸收、按最大 HP 1/4 回复、满 HP 不溢出回复，以及变化技能附加效果被阻止。",
			),
			item(
				code = "ability.element-absorb-stat",
				name = "特性吸收指定属性技能并提升能力",
				category = "特性",
				status = IMPLEMENTED,
				fixtures = listOf(
					"element-absorb-stat-ability-blocks-electric-damage-and-raises-speed",
					"element-absorb-stat-ability-blocks-grass-damage-and-raises-attack",
					"element-absorb-stat-ability-blocks-fire-damage-and-raises-defense-by-two",
				),
				references = listOf(
					"https://github.com/smogon/pokemon-showdown/blob/master/data/abilities.ts",
					"https://bulbapedia.bulbagarden.net/wiki/Motor_Drive_(Ability)",
					"https://bulbapedia.bulbagarden.net/wiki/Sap_Sipper_(Ability)",
					"https://bulbapedia.bulbagarden.net/wiki/Well-Baked_Body_(Ability)",
				),
				note = "已覆盖匹配属性技能命中目标后被特性吸收并阻止伤害，同时提升速度、攻击或防御能力阶级。",
			),
			item(
				code = "ability.element-damage-boost",
				name = "指定属性技能增伤特性",
				category = "特性",
				status = IMPLEMENTED,
				fixtures = listOf(
					"element-ability-boosts-matching-skill-damage",
				),
				references = listOf(
					"https://github.com/smogon/pokemon-showdown/blob/master/data/abilities.ts",
					"https://github.com/smogon/pokemon-showdown/blob/master/data/moves.ts",
				),
				note = "已覆盖固定属性技能按配置倍率提升伤害、非匹配属性不触发，以及天气改属性后按本次有效属性判断；龙、岩石、钢的 1.5 倍和电的约 1.3 倍规则资料已接入运行时快照。",
			),
			item(
				code = "ability.low-hp-element-boost",
				name = "低体力指定属性增伤特性",
				category = "特性",
				status = IMPLEMENTED,
				fixtures = listOf(
					"low-hp-element-ability-boosts-matching-damage-at-threshold",
				),
				references = listOf(
					"https://github.com/smogon/pokemon-showdown/blob/master/data/abilities.ts",
					"https://bulbapedia.bulbagarden.net/wiki/Swarm_(Ability)",
				),
				note = "已覆盖 HP 小于等于最大 HP 1/3 时指定属性技能获得 1.5 倍伤害倍率，并验证高于阈值或技能属性不匹配时不触发；草、火、水、虫四类低体力增伤规则资料已接入运行时快照。",
			),
			item(
				code = "ability.weather-element-damage-boost",
				name = "指定天气下属性增伤特性",
				category = "特性",
				status = IMPLEMENTED,
				fixtures = listOf(
					"weather-element-ability-boosts-matching-element-in-sandstorm",
					"ability-and-item-immunities-block-sandstorm-damage",
				),
				references = listOf(
					"https://github.com/smogon/pokemon-showdown/blob/master/data/abilities.ts",
					"https://github.com/smogon/pokemon-showdown/blob/master/data/moves.ts",
				),
				note = "已覆盖沙暴下岩石、地面和钢属性技能获得 1.3 倍特性伤害倍率，并验证天气不匹配、有效属性不匹配和天气改属性技能的判断口径；同一特性的沙暴伤害免疫通过天气伤害免疫结构化效果接入运行时快照。",
			),
			item(
				code = "ability.super-effective-damage-reduction",
				name = "效果绝佳伤害减免特性",
				category = "特性",
				status = IMPLEMENTED,
				fixtures = listOf(
					"super-effective-defensive-ability-reduces-super-effective-damage",
				),
				references = listOf(
					"https://github.com/smogon/pokemon-showdown/blob/master/data/abilities.ts",
					"https://github.com/smogon/pokemon-showdown/blob/master/sim/dex-types.ts",
				),
				note = "已覆盖防守方受到效果绝佳直接技能伤害时按 0.75 倍降低最终伤害，并验证非效果绝佳和无视目标特性时不触发；同类规则资料已接入运行时快照。",
			),
			item(
				code = "ability.full-hp-damage-reduction",
				name = "满 HP 伤害减免特性",
				category = "特性",
				status = IMPLEMENTED,
				fixtures = listOf(
					"full-hp-defensive-ability-reduces-direct-skill-damage",
				),
				references = listOf(
					"https://github.com/smogon/pokemon-showdown/blob/master/data/abilities.ts",
				),
				note = "已覆盖防守方当前 HP 等于最大 HP 时直接技能伤害按 0.5 倍降低，并验证不满 HP 和无视目标特性时不触发；同类规则资料已接入运行时快照。",
			),
			item(
				code = "ability.damage-class-damage-reduction",
				name = "按伤害分类减免特性",
				category = "特性",
				status = IMPLEMENTED,
				fixtures = listOf(
					"special-damage-class-ability-reduces-special-skill-damage",
				),
				references = listOf(
					"https://github.com/smogon/pokemon-showdown/blob/master/data/abilities.ts",
				),
				note = "已覆盖防守方受到特殊分类直接技能伤害时按 0.5 倍降低最终伤害，并验证物理分类和无视目标特性时不触发；运行时快照使用通用伤害分类集合承载该类规则。",
			),
			item(
				code = "ability.defending-stat-multiplier",
				name = "防守能力值修正特性",
				category = "特性",
				status = IMPLEMENTED,
				fixtures = listOf(
					"defense-stat-ability-doubles-physical-defense-before-damage",
					"terrain-defense-stat-ability-boosts-defense-in-grassy-terrain",
				),
				references = listOf(
					"https://github.com/smogon/pokemon-showdown/blob/master/data/abilities.ts",
				),
				note = "已覆盖物防翻倍和青草场地下物防 1.5 倍两类防御侧能力值修正；这些规则改变基础伤害公式中的防御值，而不是最终伤害倍率。",
			),
			item(
				code = "ability.attacking-stat-multiplier",
				name = "攻击能力值修正特性",
				category = "特性",
				status = IMPLEMENTED,
				fixtures = listOf(
					"attack-stat-ability-doubles-physical-attack-before-damage",
					"major-status-attack-ability-boosts-attack-and-skips-burn-drop",
				),
				references = listOf(
					"https://github.com/smogon/pokemon-showdown/blob/master/data/abilities.ts",
					"https://github.com/smogon/pokemon-showdown/blob/master/sim/battle-actions.ts",
				),
				note = "已覆盖物理攻击翻倍类特性，以及主要异常状态下物攻 1.5 倍并跳过灼伤物理减半；这些规则改变基础伤害，不进入最终伤害倍率。",
			),
			item(
				code = "ability.same-element-bonus-override",
				name = "属性一致加成覆盖特性",
				category = "特性",
				status = IMPLEMENTED,
				fixtures = listOf(
					"same-element-bonus-ability-uses-double-stab-multiplier",
				),
				references = listOf(
					"https://github.com/smogon/pokemon-showdown/blob/master/data/abilities.ts",
				),
				note = "已覆盖攻击方拥有属性一致加成覆盖特性时，技能当前有效属性与自身属性一致会把 STAB 倍率从默认 1.5 改为 2.0；该规则不进入泛用最终伤害倍率。",
			),
			item(
				code = "ability.tagged-skill-damage-boost",
				name = "特性强化指定标签技能伤害",
				category = "特性",
				status = IMPLEMENTED,
				fixtures = listOf(
					"punch-based-ability-boosts-punch-tagged-skill-damage",
					"slicing-based-ability-boosts-slicing-tagged-skill-damage",
					"contact-based-ability-boosts-contact-skill-damage",
					"sound-based-ability-boosts-sound-skill-damage",
					"sound-based-defensive-ability-reduces-sound-skill-damage",
				),
				references = listOf(
					"https://github.com/smogon/pokemon-showdown/blob/master/data/abilities.ts",
					"https://github.com/smogon/pokemon-showdown/blob/master/data/moves.ts",
				),
				note = "已覆盖拳类技能按 1.2 倍、切割类技能按 1.5 倍、接触类和声音类技能按 1.3 倍获得攻击方特性伤害倍率，并覆盖声音类技能命中防守方时 0.5 倍减伤；公式只读取结构化技能标签，不通过技能名称或文本猜测。",
			),
			item(
				code = "ability.indirect-damage-immunity",
				name = "特性免疫间接伤害",
				category = "特性",
				status = IMPLEMENTED,
				fixtures = listOf(
					"indirect-damage-immunity-blocks-residual-status-and-weather-damage",
					"indirect-damage-immunity-keeps-direct-damage-boost-but-blocks-item-recoil",
					"indirect-damage-immunity-blocks-move-recoil-and-entry-hazard-damage",
				),
				references = listOf(
					"https://github.com/smogon/pokemon-showdown/blob/master/data/abilities.ts",
					"https://bulbapedia.bulbagarden.net/wiki/Magic_Guard_(Ability)",
				),
				note = "已覆盖特性阻止异常状态回合末伤害、沙暴伤害、入场陷阱伤害、技能反作用伤害和携带道具反伤；直接技能伤害和伤害增幅道具倍率仍正常生效。",
			),
			item(
				code = "ability.skill-recoil-damage-immunity",
				name = "特性免疫技能反作用伤害",
				category = "特性",
				status = IMPLEMENTED,
				fixtures = listOf(
					"skill-recoil-immunity-blocks-move-recoil-damage",
					"skill-recoil-immunity-does-not-block-held-item-recoil",
				),
				references = listOf(
					"https://github.com/smogon/pokemon-showdown/blob/master/data/abilities.ts",
					"https://bulbapedia.bulbagarden.net/wiki/Rock_Head_(Ability)",
				),
				note = "已覆盖特性阻止技能自身反作用伤害，但不会阻止携带道具在造成伤害后产生的固定反伤。",
			),
			item(
				code = "ability.critical-hit-immunity",
				name = "特性免疫击中要害",
				category = "特性",
				status = IMPLEMENTED,
				fixtures = listOf(
					"critical-hit-immunity-blocks-guaranteed-critical-hit-damage",
					"critical-hit-immunity-blocks-successful-random-critical-hit",
				),
				references = listOf(
					"https://github.com/smogon/pokemon-showdown/blob/master/data/abilities.ts",
					"https://github.com/smogon/pokemon-showdown/blob/master/sim/battle-actions.ts",
				),
				note = "已覆盖目标特性阻止必定要害和普通随机要害；随机要害仍消费随机数，但最终伤害事件按非要害记录。",
			),
			item(
				code = "ability.ignore-opponent-damage-stat-stages",
				name = "特性无视对手伤害阶级变化",
				category = "特性",
				status = IMPLEMENTED,
				fixtures = listOf(
					"defender-stat-stage-ignore-ability-ignores-attacker-attack-boost",
					"attacker-stat-stage-ignore-ability-ignores-defender-defense-boost",
					"stat-stage-ignore-ability-applies-to-special-damage-stages",
				),
				references = listOf(
					"https://github.com/smogon/pokemon-showdown/blob/master/data/abilities.ts",
					"https://github.com/smogon/damage-calc/blob/master/calc/src/mechanics/gen789.ts",
				),
				note = "已覆盖持有者作为防守方时忽略攻击方攻击/特攻阶级、作为攻击方时忽略防守方防御/特防阶级；命中/闪避阶级由命中流程覆盖项单独验证。",
			),
			item(
				code = "ability.ignore-opponent-accuracy-stat-stages",
				name = "特性无视对手命中阶级变化",
				category = "特性",
				status = IMPLEMENTED,
				fixtures = listOf(
					"defender-accuracy-stage-ignore-ability-ignores-attacker-accuracy-drop",
					"attacker-accuracy-stage-ignore-ability-ignores-target-evasion-boost",
				),
				references = listOf(
					"https://github.com/smogon/pokemon-showdown/blob/master/data/abilities.ts",
					"https://github.com/smogon/pokemon-showdown/blob/master/sim/battle-actions.ts",
				),
				note = "已覆盖持有者作为防守方时忽略攻击方命中阶级、作为攻击方时忽略目标闪避阶级；必中和天气命中覆盖仍按原流程处理。",
			),
			item(
				code = "ability.ignore-target-ability-effects",
				name = "攻击时无视目标防守特性",
				category = "特性",
				status = IMPLEMENTED,
				fixtures = listOf(
					"target-ability-ignore-bypasses-element-absorb",
					"target-ability-ignore-bypasses-full-hp-survival",
					"target-ability-ignore-bypasses-defender-stat-stage-ignore",
					"target-ability-ignore-bypasses-target-status-immunity",
				),
				references = listOf(
					"https://github.com/smogon/pokemon-showdown/blob/master/data/abilities.ts",
					"https://github.com/smogon/pokemon-showdown/blob/master/sim/battle-actions.ts",
				),
				note = "已覆盖攻击方使用技能时跳过目标侧属性吸收、满 HP 保命、伤害阶级无视和主要异常状态免疫等防守特性；目标道具、属性天然免疫、场地免疫和非技能来源不受影响。",
			),
			item(
				code = "ability.sound-based-skill-immunity",
				name = "特性免疫声音类技能",
				category = "特性",
				status = IMPLEMENTED,
				fixtures = listOf(
					"sound-immunity-ability-blocks-sound-damaging-skill",
					"sound-immunity-ability-blocks-sound-status-skill",
					"target-ability-ignore-bypasses-sound-immunity",
				),
				references = listOf(
					"https://github.com/smogon/pokemon-showdown/blob/master/data/abilities.ts",
					"https://bulbapedia.bulbagarden.net/wiki/Soundproof_(Ability)",
				),
				note = "已覆盖目标特性在命中前阻止声音类伤害技能和声音类变化技能；攻击方无视目标特性时可以绕过该免疫。",
			),
			item(
				code = "terrain.setting-skill",
				name = "场地设置技能",
				category = "场地",
				status = IMPLEMENTED,
				fixtures = listOf("status-skill-starts-terrain-for-five-turns"),
				references = listOf(
					"https://github.com/smogon/pokemon-showdown/blob/master/data/moves.ts",
					"https://bulbapedia.bulbagarden.net/wiki/Electric_Terrain_(move)",
					"https://bulbapedia.bulbagarden.net/wiki/Grassy_Terrain_(move)",
					"https://bulbapedia.bulbagarden.net/wiki/Misty_Terrain_(move)",
					"https://bulbapedia.bulbagarden.net/wiki/Psychic_Terrain_(move)",
				),
				note = "已覆盖变化技能成功后设置电气、青草、薄雾和精神场地，普通持续 5 回合；规则资料种子已接入运行时快照。",
			),
			item(
				code = "terrain.speed-ability",
				name = "场地速度特性",
				category = "场地",
				status = IMPLEMENTED,
				fixtures = listOf(
					"terrain-speed-ability-changes-skill-action-order",
				),
				references = listOf(
					"https://github.com/smogon/pokemon-showdown/blob/master/data/abilities.ts",
					"https://bulbapedia.bulbagarden.net/wiki/Electric_Terrain_(move)",
				),
				note = "已覆盖电气场地下速度翻倍特性改变行动顺序，并已接入运行时规则资料。",
			),
			item(
				code = "field.environment-duration",
				name = "天气和场地持续回合",
				category = "天气/场地",
				status = IMPLEMENTED,
				fixtures = listOf(
					"weather-duration-decrements-and-ends",
					"terrain-duration-ends-at-turn-end",
				),
				references = listOf(
					"https://github.com/smogon/pokemon-showdown/blob/master/data/conditions.ts",
					"https://bulbapedia.bulbagarden.net/wiki/Weather",
					"https://bulbapedia.bulbagarden.net/wiki/Terrain",
				),
				note = "非永久天气/场地在回合末递减，耗尽时恢复为无并产生结束事件。",
			),
			item(
				code = "field.environment-boundaries",
				name = "天气、场地和场上状态边界",
				category = "天气/场地",
				status = IMPLEMENTED,
				fixtures = listOf(
					"weather-setting-skill-replaces-existing-weather-and-starts-new-duration",
					"terrain-setting-skill-replaces-existing-terrain-and-starts-new-duration",
					"non-matching-weather-extension-item-does-not-extend-weather-skill",
					"non-matching-terrain-extension-item-does-not-extend-terrain-skill",
					"missed-weather-setting-skill-does-not-change-weather",
					"field-speed-order-duration-decrements-without-ending",
					"field-speed-order-duration-ends-before-turn-end",
					"side-damage-reduction-duration-decrements-without-ending",
					"side-damage-reduction-duration-ends-silently",
					"side-speed-modifier-duration-decrements-without-ending",
					"side-speed-modifier-duration-ends-silently",
					"duplicate-side-damage-reduction-does-not-refresh-duration",
					"duplicate-side-speed-modifier-does-not-refresh-duration",
					"required-weather-side-condition-fails-without-weather",
					"non-matching-screen-extension-item-does-not-extend-side-damage-reduction",
					"sandstorm-damage-resolves-before-weather-healing",
					"weather-damage-uses-minimum-one-hp",
					"weather-healing-clamps-to-missing-hp",
					"grassy-terrain-healing-clamps-to-missing-hp",
					"heal-block-suppresses-weather-and-terrain-healing",
				),
				references = listOf(
					"https://github.com/smogon/pokemon-showdown/blob/master/data/conditions.ts",
					"https://github.com/smogon/pokemon-showdown/blob/master/data/moves.ts",
					"https://github.com/smogon/pokemon-showdown/blob/master/data/items.ts",
					"https://bulbapedia.bulbagarden.net/wiki/Weather",
					"https://bulbapedia.bulbagarden.net/wiki/Terrain",
				),
				note = "已覆盖天气和场地被后续技能覆盖、环境延长道具按目标匹配、命中失败不写入环境、戏法空间/屏障/顺风持续回合递减与结束、重复一侧状态不刷新、天气前置屏障失败、屏障延长道具类型不匹配、沙暴伤害与天气回复顺序、天气伤害最小 1 点、天气/场地回复夹取，以及回复封锁抑制环境回复。",
			),
			item(
				code = "weather.sun-rain-damage",
				name = "天气核心效果",
				category = "天气",
				status = IMPLEMENTED,
				fixtures = listOf(
					"sun-boosts-fire-and-weakens-water-damage",
					"rain-boosts-water-and-weakens-fire-damage",
					"weather-power-multiplier-modifies-base-power",
					"sandstorm-boosts-rock-special-defense",
					"snow-boosts-ice-physical-defense",
					"sandstorm-damages-only-non-immune-active-participants",
					"weather-speed-ability-changes-skill-action-order",
					"ability-and-item-immunities-block-sandstorm-damage",
					"weather-accuracy-overrides-support-sure-hit-and-lowered-accuracy",
					"weather-element-override-participates-in-stab-weather-and-effectiveness",
					"weather-element-override-can-be-absorbed-by-matching-element-ability",
					"weather-element-override-to-fire-thaws-frozen-target",
				),
				references = listOf(
					"https://github.com/smogon/pokemon-showdown/blob/master/data/conditions.ts",
					"https://github.com/smogon/pokemon-showdown/blob/master/data/moves.ts",
					"https://github.com/smogon/pokemon-showdown/blob/master/data/abilities.ts",
					"https://github.com/smogon/pokemon-showdown/blob/master/data/items.ts",
					"https://bulbapedia.bulbagarden.net/wiki/Weather",
				),
				note = "已覆盖晴雨火水伤害倍率、天气威力/属性/命中例外、沙暴岩属性特防、雪景冰属性物防、沙暴固定伤害、天气速度特性和天气伤害免疫；天气速度特性和天气属性覆盖的规则资料种子已接入运行时快照。",
			),
			item(
				code = "weather.healing-ability",
				name = "天气回复特性",
				category = "天气",
				status = IMPLEMENTED,
				fixtures = listOf("weather-healing-ability-heals-active-participant-at-end-turn"),
				references = listOf(
					"https://github.com/smogon/pokemon-showdown/blob/master/data/abilities.ts",
					"https://bulbapedia.bulbagarden.net/wiki/Weather",
				),
				note = "已覆盖指定天气存在时，当前上场未满 HP 成员按最大 HP 1/16 回复；规则资料种子已接入运行时快照。",
			),
			item(
				code = "weather.setting-skill",
				name = "天气设置技能",
				category = "天气",
				status = IMPLEMENTED,
				fixtures = listOf("status-skill-starts-weather-for-five-turns"),
				references = listOf(
					"https://github.com/smogon/pokemon-showdown/blob/master/data/moves.ts",
					"https://bulbapedia.bulbagarden.net/wiki/Rain_Dance_(move)",
					"https://bulbapedia.bulbagarden.net/wiki/Sunny_Day_(move)",
					"https://bulbapedia.bulbagarden.net/wiki/Sandstorm_(move)",
					"https://bulbapedia.bulbagarden.net/wiki/Snowscape_(move)",
				),
				note = "已覆盖变化技能成功后设置雨天、晴天、沙暴和雪天天气，普通持续 5 回合；规则资料种子已接入运行时快照。",
			),
			item(
				code = "status.freeze",
				name = "冰冻和解冻流程",
				category = "主要状态",
				status = IMPLEMENTED,
				fixtures = listOf(
					"freeze-prevents-action-after-failed-thaw-roll",
					"freeze-thaws-before-action-and-continues",
					"fire-damage-thaws-frozen-target-that-survives",
					"self-thawing-skill-can-be-used-while-frozen",
				),
				references = listOf(
					"https://github.com/smogon/pokemon-showdown/blob/master/data/conditions.ts",
					"https://bulbapedia.bulbagarden.net/wiki/Freeze_(status_condition)",
				),
				note = "已覆盖行动前自然解冻、未解冻阻止行动、被火属性伤害命中后解冻，以及带标签技能自解冻。",
			),
			item(
				code = "status.immunity-and-grounding",
				name = "状态免疫和是否接地",
				category = "免疫",
				status = IMPLEMENTED,
				fixtures = listOf(
					"element-immunities-block-major-statuses",
					"electric-terrain-does-not-block-sleep-for-ungrounded-target",
					"misty-terrain-blocks-major-status-for-grounded-target",
					"grass-target-blocks-powder-based-status-skill",
					"grassy-terrain-heals-only-grounded-active-participants",
					"existing-major-status-blocks-new-major-status",
					"ability-and-item-immunities-block-matching-major-statuses",
					"terrain-ability-and-item-immunities-block-confusion-before-duration-random",
					"ability-and-item-immunities-block-flinch-before-action",
				),
				references = listOf(
					"https://github.com/smogon/pokemon-showdown/blob/master/data/conditions.ts",
					"https://github.com/smogon/pokemon-showdown/blob/master/data/abilities.ts",
					"https://github.com/smogon/pokemon-showdown/blob/master/data/items.ts",
				),
				note = "已覆盖已有主要状态阻止覆盖、主要状态属性免疫、粉末类技能草属性免疫、接地场地免疫、青草场地接地回复，以及特性/道具提供的主要状态、混乱和畏缩免疫。",
			),
			item(
				code = "ability.switch-in-stat-stage",
				name = "出场特性能力阶级变化",
				category = "特性",
				status = IMPLEMENTED,
				fixtures = listOf(
					"switch-in-attack-drop-triggers-at-battle-start",
					"switch-in-attack-drop-targets-both-double-battle-opponents",
					"switch-in-attack-drop-triggers-after-voluntary-switch",
				),
				references = listOf(
					"https://github.com/smogon/pokemon-showdown/blob/master/data/abilities.ts",
					"https://bulbapedia.bulbagarden.net/wiki/Intimidate_(Ability)",
				),
				note = "已覆盖战斗开始和主动换入时触发出场降攻特性，单打影响当前对手，双打影响对方两个当前上场成员。",
			),
			item(
				code = "ability.switch-in-weather",
				name = "出场特性设置天气",
				category = "特性",
				status = IMPLEMENTED,
				fixtures = listOf(
					"switch-in-weather-starts-rain-at-battle-start",
					"slower-switch-in-weather-overwrites-faster-weather-at-battle-start",
					"switch-in-weather-triggers-after-voluntary-switch",
				),
				references = listOf(
					"https://github.com/smogon/pokemon-showdown/blob/master/data/abilities.ts",
					"https://github.com/smogon/pokemon-showdown/blob/master/data/conditions.ts",
					"https://bulbapedia.bulbagarden.net/wiki/Weather#Abilities_that_create_weather",
				),
				note = "已覆盖出场设置普通天气、战斗开始多天气按有效速度顺序覆盖，以及主动换入后的天气触发。",
			),
			item(
				code = "ability.switch-in-terrain",
				name = "出场特性设置场地",
				category = "特性",
				status = IMPLEMENTED,
				fixtures = listOf(
					"switch-in-terrain-starts-electric-terrain-at-battle-start",
					"slower-switch-in-terrain-overwrites-faster-terrain-at-battle-start",
					"switch-in-terrain-triggers-after-voluntary-switch",
				),
				references = listOf(
					"https://github.com/smogon/pokemon-showdown/blob/master/data/abilities.ts",
					"https://bulbapedia.bulbagarden.net/wiki/Terrain#Abilities_that_create_terrain",
				),
				note = "已覆盖出场设置普通场地、战斗开始多场地按有效速度顺序覆盖，以及主动换入后的场地触发。",
			),
			item(
				code = "ability.contact-status",
				name = "接触类特性返还异常状态",
				category = "特性",
				status = IMPLEMENTED,
				fixtures = listOf(
					"contact-status-ability-applies-paralysis-after-contact",
					"contact-status-ability-misses-when-chance-roll-fails",
					"contact-status-ability-respects-attacker-immunity",
				),
				references = listOf(
					"https://github.com/smogon/pokemon-showdown/blob/master/data/abilities.ts",
					"https://bulbapedia.bulbagarden.net/wiki/Static_(Ability)",
					"https://bulbapedia.bulbagarden.net/wiki/Flame_Body_(Ability)",
					"https://bulbapedia.bulbagarden.net/wiki/Limber_(Ability)",
				),
				note = "已覆盖接触类技能成功造成伤害后触发目标特性，100% 概率不额外消费随机数，30% 概率失败时不附加状态，并复用攻击方主要异常免疫流程。",
			),
			item(
				code = "damage.full-hp-survival",
				name = "满 HP 致命伤害保留 1 HP",
				category = "伤害",
				status = IMPLEMENTED,
				fixtures = listOf(
					"full-hp-survival-ability-leaves-one-hp-before-faint",
					"consumable-full-hp-survival-item-leaves-one-hp-and-consumes-item",
					"full-hp-survival-does-not-trigger-after-prior-damage",
				),
				references = listOf(
					"https://github.com/smogon/pokemon-showdown/blob/master/data/abilities.ts",
					"https://github.com/smogon/pokemon-showdown/blob/master/data/items.ts",
					"https://bulbapedia.bulbagarden.net/wiki/Sturdy_(Ability)",
					"https://bulbapedia.bulbagarden.net/wiki/Focus_Sash",
				),
				note = "已覆盖满 HP 被技能直接伤害一击打倒前由特性或一次性携带道具保留 1 HP；道具来源会在触发后被消费，非满 HP 不触发。",
			),
				item(
					code = "item.held-core-effects",
					name = "携带道具核心触发效果",
				category = "道具",
				status = IMPLEMENTED,
				fixtures = listOf(
					"low-hp-berry-heals-once-after-damage",
					"choice-speed-item-modifies-action-order",
					"damage-boost-item-uses-max-hp-recoil-after-damage",
					"damage-dealt-healing-item-restores-eighth-actual-damage",
					"damage-dealt-healing-item-counts-substitute-damage",
					"damage-dealt-healing-item-uses-total-multi-hit-damage",
					"end-turn-healing-item-restores-one-sixteenth-max-hp",
					"weather-extending-item-makes-weather-skill-last-eight-turns",
					"weather-extending-item-makes-weather-ability-last-eight-turns",
					"terrain-extending-item-makes-terrain-skill-last-eight-turns",
					"terrain-extending-item-makes-terrain-ability-last-eight-turns",
				),
				references = listOf(
					"https://github.com/smogon/pokemon-showdown/blob/master/data/items.ts",
					"https://bulbapedia.bulbagarden.net/wiki/Oran_Berry",
					"https://bulbapedia.bulbagarden.net/wiki/Sitrus_Berry",
					"https://bulbapedia.bulbagarden.net/wiki/Life_Orb",
					"https://bulbapedia.bulbagarden.net/wiki/Shell_Bell",
					"https://bulbapedia.bulbagarden.net/wiki/Leftovers",
					"https://bulbapedia.bulbagarden.net/wiki/Damp_Rock",
					"https://bulbapedia.bulbagarden.net/wiki/Terrain_Extender",
				),
					note = "已覆盖低体力树果一次性回复并消费、讲究类速度道具改变行动顺序并锁定首次技能、生命宝珠类伤害增幅按最大 HP 反伤、贝壳之铃类按整次技能实际总伤害回复、剩饭类回合末最大 HP 1/16 回复，以及天气/场地延长道具把普通环境技能或出场环境特性的持续回合改为 8。",
				),
				item(
					code = "item.element-damage-boost",
					name = "携带道具指定属性伤害提升",
					category = "道具",
					status = IMPLEMENTED,
					fixtures = listOf(
						"element-damage-boost-item-multiplies-matching-damage",
						"element-damage-boost-item-ignores-non-matching-damage",
					),
					references = listOf(
						"https://github.com/smogon/pokemon-showdown/blob/master/data/items.ts",
						"https://bulbapedia.bulbagarden.net/wiki/Type-enhancing_item",
					),
					note = "已覆盖传统非消耗型属性强化道具：技能属性匹配时有效威力按 1.2 倍参与普通伤害公式，不匹配时保持中性，且不会消费道具或产生反伤。规则资料已接入现代 18 个属性的对应道具。",
				),
				item(
					code = "item.element-damage-reduction",
					name = "携带道具指定属性伤害减免",
					category = "道具",
					status = IMPLEMENTED,
					fixtures = listOf(
						"element-damage-reduction-item-halves-super-effective-damage",
						"element-damage-reduction-item-requires-super-effective-damage",
						"element-damage-reduction-item-does-not-activate-through-substitute",
						"normal-damage-reduction-item-halves-normal-damage",
					),
					references = listOf(
						"https://github.com/smogon/pokemon-showdown/blob/master/data/items.ts",
						"https://github.com/smogon/pokemon-showdown/blob/master/data/conditions.ts",
						"https://bulbapedia.bulbagarden.net/wiki/Damage-reducing_Berry",
						"https://bulbapedia.bulbagarden.net/wiki/Chilan_Berry",
					),
					note = "已覆盖抗性树果在本体受到对应属性且效果绝佳伤害时按 0.5 倍减伤并消费、命中替身时不触发，以及一般属性灯浆果不要求效果绝佳的例外。规则资料已接入现代 18 个属性的对应抗性树果。",
				),
				item(
					code = "item.conditional-damage-boost",
					name = "携带道具条件伤害提升",
					category = "道具",
					status = IMPLEMENTED,
					fixtures = listOf(
						"physical-power-boost-item-raises-matching-damage-class",
						"physical-power-boost-item-ignores-special-damage-class",
						"super-effective-damage-boost-item-raises-final-damage",
						"super-effective-damage-boost-item-ignores-neutral-damage",
					),
					references = listOf("https://github.com/smogon/pokemon-showdown/blob/master/data/items.ts"),
					note = "已覆盖物理/特殊分类威力提升道具在威力阶段生效，以及效果绝佳伤害提升道具在最终伤害阶段生效；三者均不消费道具、不反伤、不锁招。",
				),
				item(
					code = "item.major-status-cure",
					name = "携带道具解除主要异常状态",
					category = "道具",
					status = IMPLEMENTED,
					fixtures = listOf(
						"major-status-cure-item-clears-status-after-application",
						"major-status-cure-item-clears-contact-ability-status",
						"specific-status-cure-item-keeps-unmatched-status",
					),
					references = listOf(
						"https://github.com/smogon/pokemon-showdown/blob/master/data/items.ts",
						"https://bulbapedia.bulbagarden.net/wiki/Lum_Berry",
						"https://bulbapedia.bulbagarden.net/wiki/Chesto_Berry",
						"https://bulbapedia.bulbagarden.net/wiki/Rawst_Berry",
					),
					note = "已覆盖主要异常状态成功写入后由携带道具立即解除并消费；技能附加状态和接触特性返还状态共用同一 after-status 钩子，非匹配状态不会消费道具。规则资料已接入全状态解除，以及麻痹、睡眠、中毒、灼伤、冰冻的指定状态解除道具。",
				),
				item(
					code = "item.volatile-status-cure",
					name = "携带道具解除临时状态",
					category = "道具",
					status = IMPLEMENTED,
					fixtures = listOf(
						"volatile-status-cure-item-clears-confusion-after-application",
					),
					references = listOf(
						"https://github.com/smogon/pokemon-showdown/blob/master/data/items.ts",
						"https://github.com/smogon/pokemon-showdown/blob/master/data/conditions.ts",
						"https://bulbapedia.bulbagarden.net/wiki/Persim_Berry",
						"https://bulbapedia.bulbagarden.net/wiki/Confusion_(status_condition)",
					),
					note = "已覆盖混乱成功写入并消费持续时间随机数后，由携带道具立即解除混乱并消费自身。该规则使用独立临时状态治愈模型，不与主要异常状态混用。",
				),
				item(
					code = "turn.multi-hit-and-locked-move",
					name = "多段技能和锁招混乱",
				category = "技能流程",
				status = IMPLEMENTED,
				fixtures = listOf(
					"multi-hit-skill-consumes-pp-once-and-applies-scripted-hit-count",
					"multi-hit-skill-stops-after-target-faints",
					"locked-move-overrides-submitted-skill-follows-target-slot-and-confuses",
					"locked-move-prevents-voluntary-switch-and-executes-continuation",
					"locked-move-disruption-before-final-turn-clears-lock-without-fatigue-confusion",
				),
				references = listOf(
					"https://github.com/smogon/pokemon-showdown/blob/master/data/conditions.ts",
					"https://github.com/smogon/pokemon-showdown/blob/master/data/moves.ts",
					"https://bulbapedia.bulbagarden.net/wiki/Outrage_(move)",
					"https://pokemondb.net/move/outrage",
				),
				note = "已覆盖 2..5 段命中分布、单次 PP 消耗、倒下中断、锁招续回合、目标槽位重定向、主动替换阻止和疲劳混乱。",
			),
			item(
				code = "turn.recharge-after-use",
				name = "成功后休整技能",
				category = "技能流程",
				status = IMPLEMENTED,
				fixtures = listOf(
					"recharge-skill-prevents-next-turn-action-without-pp-loss",
				),
				references = listOf(
					"https://github.com/smogon/pokemon-showdown/blob/master/data/moves.ts",
					"https://bulbapedia.bulbagarden.net/wiki/Hyper_Beam_(move)",
				),
				note = "已覆盖成功造成实际伤害后写入一次休整、下一次技能行动前阻止执行且不扣 PP，以及主动替换校验阻止；未造成实际伤害时不会进入休整。",
			),
			item(
				code = "turn.charge-before-use",
				name = "蓄力后发动技能",
				category = "技能流程",
				status = IMPLEMENTED,
				fixtures = listOf(
					"charge-skill-releases-next-turn-without-extra-pp",
					"charge-skill-skips-charge-in-sun",
					"charge-skill-consumes-item-to-skip-charge",
				),
				references = listOf(
					"https://github.com/smogon/pokemon-showdown/blob/master/data/moves.ts",
					"https://github.com/smogon/pokemon-showdown/blob/master/data/items.ts",
					"https://bulbapedia.bulbagarden.net/wiki/Solar_Beam_(move)",
					"https://bulbapedia.bulbagarden.net/wiki/Power_Herb",
				),
				note = "已覆盖首次使用消耗 PP 并进入蓄力、下一次技能行动自动释放且不重复扣 PP、主动替换阻止、指定天气跳过蓄力、一次性道具消费后同回合释放，以及释放阶段复用普通命中和伤害流程。",
			),
			item(
				code = "turn.substitute",
				name = "替身建立、代伤和状态阻止",
				category = "技能流程",
				status = IMPLEMENTED,
				fixtures = listOf(
					"substitute-pays-quarter-max-hp-and-absorbs-damage-until-broken",
					"substitute-keeps-remaining-hp-after-partial-damage",
					"substitute-blocks-opponent-major-status",
					"substitute-blocks-opponent-volatile-status",
					"sound-damage-skill-bypasses-substitute",
					"sound-status-skill-bypasses-substitute",
				),
				references = listOf(
					"https://github.com/smogon/pokemon-showdown/blob/master/data/moves.ts",
					"https://github.com/smogon/pokemon-showdown/blob/master/data/conditions.ts",
					"https://bulbapedia.bulbagarden.net/wiki/Substitute_(move)",
					"https://bulbapedia.bulbagarden.net/wiki/Sound-based_move",
				),
				note = "已覆盖支付最大 HP 1/4 建立替身、对手普通伤害先扣替身 HP、替身破裂或保留剩余 HP、替身阻止对手主要异常状态和混乱等临时状态、普通降能力变化技被替身阻止，以及声音类伤害和声音类变化技穿过替身。",
			),
			item(
				code = "skill.major-status-effects",
				name = "技能主要异常状态附加",
				category = "技能效果",
				status = IMPLEMENTED,
				fixtures = listOf(
					"status-skill-applies-burn-and-end-turn-residual-damage",
					"grass-target-blocks-powder-based-status-skill",
					"sleep-prevents-two-actions-from-scripted-duration",
				),
				references = listOf(
					"https://github.com/smogon/pokemon-showdown/blob/master/data/moves.ts",
					"https://bulbapedia.bulbagarden.net/wiki/Will-O-Wisp_(move)",
					"https://bulbapedia.bulbagarden.net/wiki/Powder_and_spore_moves",
					"https://bulbapedia.bulbagarden.net/wiki/Sleep_(status_condition)",
				),
				note = "已覆盖变化技能附加灼伤、中毒、麻痹和睡眠，粉末类技能标签与草属性免疫，以及睡眠持续行动阻止；基础状态类技能规则资料已接入运行时快照。",
			),
			item(
				code = "skill.stat-stage-effects",
				name = "技能能力阶级变化",
				category = "技能效果",
				status = IMPLEMENTED,
				fixtures = listOf(
					"stat-stage-effect-changes-later-action-damage-in-the-same-turn",
					"status-skill-applies-multiple-user-stat-stage-changes",
					"all-opponents-status-skill-applies-stat-stage-change-to-each-active-opponent",
				),
				references = listOf(
					"https://github.com/smogon/pokemon-showdown/blob/master/data/moves.ts",
					"https://bulbapedia.bulbagarden.net/wiki/Stat_modifier",
					"https://bulbapedia.bulbagarden.net/wiki/Swords_Dance_(move)",
					"https://bulbapedia.bulbagarden.net/wiki/Shell_Smash_(move)",
				),
				note = "已覆盖命中后降低目标能力阶级、变化技能提升使用者单项或多项能力阶级、双打全体对手逐个降阶，并已接入基础自我强化和目标降阶技能规则资料。",
			),
			item(
				code = "skill.stat-stage-operations",
				name = "技能能力阶级特殊操作",
				category = "技能效果",
				status = IMPLEMENTED,
				fixtures = listOf(
					"damaging-skill-clears-target-stat-stages-after-hit",
					"status-skill-clears-every-active-participant-stat-stages",
					"status-skill-copies-target-stat-stages-to-user",
					"status-skill-swaps-attack-stat-stages-between-user-and-target",
					"status-skill-swaps-defense-stat-stages-between-user-and-target",
					"status-skill-swaps-all-stat-stages-between-user-and-target",
					"status-skill-inverts-target-stat-stages",
				),
				references = listOf(
					"https://github.com/smogon/pokemon-showdown/blob/master/data/moves.ts",
					"https://bulbapedia.bulbagarden.net/wiki/Clear_Smog_(move)",
					"https://bulbapedia.bulbagarden.net/wiki/Haze_(move)",
					"https://bulbapedia.bulbagarden.net/wiki/Psych_Up_(move)",
					"https://bulbapedia.bulbagarden.net/wiki/Power_Swap_(move)",
					"https://bulbapedia.bulbagarden.net/wiki/Guard_Swap_(move)",
					"https://bulbapedia.bulbagarden.net/wiki/Heart_Swap_(move)",
					"https://bulbapedia.bulbagarden.net/wiki/Topsy-Turvy_(move)",
				),
				note = "已覆盖命中后清除目标能力阶级、全场清除当前上场成员能力阶级、复制目标阶级给使用者、交换攻击组、防御组和全部能力阶级，以及取反目标能力阶级。",
			),
			item(
				code = "skill.hp-effects",
				name = "技能 HP 回复效果",
				category = "技能效果",
				status = IMPLEMENTED,
				fixtures = listOf(
					"draining-damage-skill-heals-user-by-half-damage-dealt",
					"draining-damage-skill-honors-configured-drain-fraction",
					"self-healing-status-skill-restores-half-max-hp",
					"weather-sensitive-self-healing-skill-uses-current-weather-fraction",
					"recoil-damage-skill-uses-target-hp-actually-lost",
				),
				references = listOf(
					"https://github.com/smogon/pokemon-showdown/blob/master/data/moves.ts",
					"https://bulbapedia.bulbagarden.net/wiki/Absorb_(move)",
					"https://bulbapedia.bulbagarden.net/wiki/Draining_Kiss_(move)",
					"https://bulbapedia.bulbagarden.net/wiki/Recover_(move)",
					"https://bulbapedia.bulbagarden.net/wiki/Synthesis_(move)",
					"https://bulbapedia.bulbagarden.net/wiki/Double-Edge_(move)",
				),
				note = "已覆盖造成伤害后按实际伤害 1/2 或 3/4 吸取回复、变化技能固定 1/2 自我回复、晨光/光合作用/月光类天气变量回复，以及按目标实际损失 HP 计算的技能反作用伤害。",
			),
			item(
				code = "skill.effect-boundaries",
				name = "技能效果边界",
				category = "技能效果",
				status = IMPLEMENTED,
				fixtures = listOf(
					"drain-healing-clamps-to-missing-hp",
					"drain-healing-minimum-one-after-one-damage",
					"drain-healing-skips-full-hp-user",
					"recoil-damage-clamps-to-user-current-hp",
					"recoil-damage-immunity-skips-skill-recoil",
					"self-healing-clamps-to-missing-hp",
					"self-healing-skips-full-hp-user",
					"weather-sensitive-self-healing-uses-default-fraction-without-weather",
					"forced-switch-single-bench-consumes-no-random",
					"forced-switch-skips-when-target-side-has-no-bench",
					"forced-switch-skips-target-fainted-by-damage",
					"substitute-blocks-forced-switch-effect",
					"forced-switch-triggers-entry-hazard-on-replacement",
					"stat-stage-effect-chance-failure-consumes-random-without-change",
					"stat-stage-effect-at-upper-bound-produces-no-event",
					"stat-stage-operation-chance-failure-consumes-random-without-change",
					"clear-operation-at-zero-produces-no-event",
					"copy-operation-with-same-stage-produces-no-event",
					"swap-operation-with-same-stage-produces-no-event",
					"invert-operation-at-zero-produces-no-event",
				),
				references = listOf(
					"https://github.com/smogon/pokemon-showdown/blob/master/data/moves.ts",
					"https://github.com/smogon/pokemon-showdown/blob/master/sim/battle-actions.ts",
					"https://github.com/smogon/pokemon-showdown/blob/master/data/conditions.ts",
					"https://bulbapedia.bulbagarden.net/wiki/Stat_modifier",
				),
				note = "已覆盖吸取回复缺失 HP 夹取、1 点实际伤害最小吸取回复、满 HP 跳过吸取回复、技能反作用伤害按使用者当前 HP 夹取、反作用免疫、主动回复夹取与满 HP 跳过、天气变量回复默认比例、强制替换单后备不消费随机、无后备/目标倒下/替身阻挡时短路、强制替换后接续入场陷阱，以及普通能力阶级效果和清除/复制/交换/取反操作在概率失败、能力边界或无变化时不产生误导性事件。",
			),
			item(
				code = "ability-item.effect-boundaries",
				name = "特性和道具效果边界",
				category = "特性/道具",
				status = IMPLEMENTED,
				fixtures = listOf(
					"element-absorb-heal-ignores-non-matching-element",
					"element-absorb-heal-waits-for-hit-and-skips-on-miss",
					"element-absorb-stat-at-upper-bound-absorbs-without-stage-event",
					"target-ability-ignore-does-not-bypass-held-damage-reduction-item",
					"target-ability-ignore-keeps-same-side-target-ability-active",
					"sound-immunity-does-not-block-user-own-sound-skill",
					"sound-immunity-ignores-non-sound-skill",
					"priority-side-immunity-ignores-same-side-priority-support",
					"priority-side-immunity-ignores-non-priority-skill",
					"priority-side-immunity-can-be-bypassed-by-target-ability-ignore",
					"weather-damage-immunity-requires-matching-weather",
					"weather-healing-ability-requires-matching-weather",
					"weather-speed-multiplier-requires-matching-weather",
					"terrain-speed-multiplier-requires-matching-terrain",
					"damage-dealt-healing-item-clamps-to-missing-hp",
					"damage-dealt-healing-item-skips-full-hp-user",
					"low-hp-healing-item-clamps-to-missing-hp-and-consumes",
					"low-hp-healing-item-skips-fainted-holder",
					"held-end-turn-healing-item-clamps-to-missing-hp",
					"non-consumable-element-damage-reduction-keeps-held-item",
				),
				references = listOf(
					"https://github.com/smogon/pokemon-showdown/blob/master/data/abilities.ts",
					"https://github.com/smogon/pokemon-showdown/blob/master/data/items.ts",
					"https://github.com/smogon/pokemon-showdown/blob/master/sim/battle-actions.ts",
					"https://bulbapedia.bulbagarden.net/wiki/Weather",
					"https://bulbapedia.bulbagarden.net/wiki/Terrain",
				),
				note = "已覆盖属性吸收特性非匹配与未命中短路、吸收提阶上限、无视目标特性不影响同侧目标或携带道具、声音免疫与先制侧防护的敌我和标签边界、天气/场地速度和回复特性只在环境匹配时生效，以及造成伤害后回复、低体力回复、回合末回复和抗性减伤道具在满 HP、倒下、夹取和非消耗配置下的稳定行为。",
			),
			item(
				code = "format-lifecycle.boundaries",
				name = "格式和生命周期边界",
				category = "格式/生命周期",
				status = IMPLEMENTED,
				fixtures = listOf(
					"format-rejects-blank-code",
					"format-rejects-default-level-below-one",
					"format-rejects-zero-max-turns",
					"initial-state-rejects-duplicate-side-ids",
					"initial-state-rejects-active-count-mismatch",
					"preparation-validator-collects-direct-restrictions-on-one-participant",
					"preparation-validator-records-duplicate-item-resource-ids",
					"preparation-validator-ignores-duplicate-clauses-when-disabled",
					"action-validator-reports-missing-actor",
					"action-validator-reports-bench-actor-is-not-active",
					"action-validator-reports-fainted-active-skill-user",
					"action-validator-reports-target-is-not-active",
					"action-validator-reports-fainted-active-target",
					"action-validator-reports-switch-target-already-active",
					"battle-ended-validation-keeps-specific-action-violations",
					"participant-faint-event-precedes-battle-ended-event",
					"battle-ending-turn-does-not-append-normal-turn-ended",
					"simultaneous-last-participants-faint-produces-draw-result",
					"switch-out-clears-disable-taunt-torment-and-heal-block",
					"forced-switch-clears-binding-locked-choice-and-substitute-state",
				),
				references = listOf(
					"https://github.com/smogon/pokemon-showdown/blob/master/config/formats.ts",
					"https://github.com/smogon/pokemon-showdown/blob/master/sim/battle-actions.ts",
					"https://github.com/smogon/pokemon-showdown/blob/master/sim/battle-queue.ts",
					"https://github.com/smogon/pokemon-showdown/blob/master/sim/pokemon.ts",
					"https://wiki.52poke.com/wiki/对战",
				),
				note = "已覆盖格式 code、默认等级、最大回合数和初始阵营/上场席位不变量；准备阶段多重限制聚合、重复条款开关和资源 ID；行动提交阶段成员、目标、替换和战斗结束后的结构化违规；以及濒死先于胜负、终局回合不追加普通回合结束、双方同时倒下平局和离场清理临时运行态。",
			),
			item(
				code = "final.rule-boundaries",
				name = "最终规则边界收口",
				category = "最终覆盖",
				status = IMPLEMENTED,
				fixtures = listOf(
					"unprotected-damaging-skill-bypasses-protection-and-still-deals-damage",
					"selected-target-fainted-before-later-action-cancels-skill-use",
					"all-active-stat-clear-skips-bench-participants",
					"zero-chance-major-status-effect-consumes-no-random-and-applies-nothing",
					"zero-chance-volatile-effect-skips-duration-random",
					"copy-operation-changes-only-declared-stat",
					"swap-operation-writes-both-participants-in-one-effect",
					"invert-operation-turns-negative-stage-positive",
					"charge-skip-item-is-consumed-before-protection-blocks-released-skill",
					"fatal-survival-item-consumption-prevents-low-hp-heal-on-same-hit",
					"non-consumable-major-status-cure-keeps-held-item",
					"non-consumable-volatile-status-cure-keeps-held-item",
				),
				references = listOf(
					"https://github.com/smogon/pokemon-showdown/blob/master/sim/battle-actions.ts",
					"https://github.com/smogon/pokemon-showdown/blob/master/data/moves.ts",
					"https://github.com/smogon/pokemon-showdown/blob/master/data/items.ts",
					"https://github.com/smogon/pokemon-showdown/blob/master/data/conditions.ts",
					"https://bulbapedia.bulbagarden.net/wiki/Stat_modifier",
				),
				note = "已覆盖不受保护影响技能穿过保护、目标在行动前倒下取消后续技能、全场能力清除不影响后备、0% 主要/临时状态效果不消费随机、复制/交换/取反能力阶级只改写声明能力项，以及蓄力跳过、免死、主要异常治愈和临时状态治愈道具的消费边界。最终账本 312 条规则行为已全部完成公开对照。",
			),
			item(
				code = "skill.forced-switch",
				name = "技能强制替换目标",
				category = "技能效果",
				status = IMPLEMENTED,
				fixtures = listOf(
					"status-skill-forces-target-side-random-bench-switch",
					"damaging-skill-applies-damage-before-forced-target-switch",
				),
				references = listOf(
					"https://github.com/smogon/pokemon-showdown/blob/master/data/moves.ts",
					"https://bulbapedia.bulbagarden.net/wiki/Roar_(move)",
					"https://bulbapedia.bulbagarden.net/wiki/Whirlwind_(move)",
					"https://bulbapedia.bulbagarden.net/wiki/Circle_Throw_(move)",
					"https://bulbapedia.bulbagarden.net/wiki/Dragon_Tail_(move)",
				),
				note = "已覆盖变化技能命中后随机强制目标侧后备换入，以及伤害技能先造成普通伤害再强制目标侧后备换入；换入继续触发入场陷阱和出场特性流程。",
			),
		)

	private fun item(
		code: String,
		name: String,
		category: String,
		status: String,
		fixtures: List<String>,
		references: List<String>,
		note: String,
	): BattleRuleCoverageItemResponse =
		BattleRuleCoverageItemResponse(
			code = code,
			name = name,
			category = category,
			status = status,
			fixtureNames = fixtures,
			referenceUrls = references,
			note = note,
		)

	private companion object {
		private const val IMPLEMENTED = "IMPLEMENTED"
		private const val PARTIAL = "PARTIAL"
		private const val PLANNED = "PLANNED"
		private const val CHECK_PASSED = "PASSED"
		private const val CHECK_FAILED = "FAILED"
		private const val FINAL_TARGET_RULE_COUNT = 312
		private const val FINAL_COVERED_RULE_COUNT = 312
		private const val REQUIRED_TARGET_RULE_COUNT = 312
		private const val GOLDEN_REPLAY_COVERAGE_CODE = "replay.deterministic-random-trace"
		private val RULE_STATUSES = setOf(IMPLEMENTED, PARTIAL, PLANNED)
		private const val FINAL_TARGET_BASIS =
			"按可复用规则行为族统计，详见 docs/superpowers/plans/2026-06-29-battle-rule-final-coverage-ledger.md。"
	}
}
