-- IAM 基础用户、角色、菜单和权限来自 avalon-spring 的 0.0.1 初始化数据，仅保留当前后端已落地能力。
INSERT INTO iam.role (code, name, enabled)
VALUES ('ROLE_SUPER_ADMIN', '超级管理员', TRUE),
       ('ROLE_TEST', '测试员', TRUE);

INSERT INTO iam.user_account (
    username,
    phone,
    email,
    avatar,
    enabled,
    password_hash,
    username_normalized,
    email_normalized,
    phone_normalized,
    password_updated_at
)
VALUES (
    'admin',
    '13800000000',
    'admin@example.com',
    NULL,
    TRUE,
    '$2a$10$IlYJ6qn4gyXUL.CCLzlN4ujjzlfI.3UbB0VQrYSUmiaPKpcnxdU.G',
    'admin',
    'admin@example.com',
    '13800000000',
    CURRENT_TIMESTAMP
);

INSERT INTO iam.user_role (user_id, role_id)
SELECT user_account.id, role.id
FROM (VALUES ('admin', 'ROLE_SUPER_ADMIN'), ('admin', 'ROLE_TEST')) AS binding(username, role_code)
JOIN iam.user_account ON iam.user_account.username = binding.username
JOIN iam.role ON iam.role.code = binding.role_code;

INSERT INTO iam.menu (
    disabled,
    extra,
    icon,
    menu_key,
    title,
    visible,
    path,
    route_name,
    redirect,
    component,
    sorting_order,
    pinned,
    show_tab,
    enable_multi_tab,
    menu_type,
    hidden,
    hide_children_in_menu,
    flat_menu,
    active_menu,
    external,
    target
)
VALUES (FALSE, NULL, 'mage:dashboard-chart', 'dashboard', '仪表板', TRUE, '/dashboard', 'dashboard', NULL,
        'dashboard/index', 0, TRUE, TRUE, FALSE, 'menu', FALSE, FALSE, FALSE, NULL, FALSE, NULL),
       (FALSE, NULL, 'ph:diamonds-four', 'iam', '身份访问', TRUE, '/iam', 'iam', NULL, 'iam', 0, FALSE, TRUE,
        FALSE, 'directory', FALSE, FALSE, FALSE, NULL, FALSE, NULL),
       (FALSE, NULL, 'ic:outline-dataset', 'catalog', '图鉴目录', TRUE, '/catalog', 'catalog', NULL, 'catalog', 0,
        FALSE, TRUE, FALSE, 'directory', FALSE, FALSE, FALSE, NULL, FALSE, NULL);

INSERT INTO iam.menu (
    parent_id,
    disabled,
    extra,
    icon,
    menu_key,
    title,
    visible,
    path,
    route_name,
    redirect,
    component,
    sorting_order,
    pinned,
    show_tab,
    enable_multi_tab,
    menu_type,
    hidden,
    hide_children_in_menu,
    flat_menu,
    active_menu,
    external,
    target
)
SELECT parent.id,
       menu.disabled,
       menu.extra,
       menu.icon,
       menu.menu_key,
       menu.title,
       menu.visible,
       menu.path,
       menu.route_name,
       menu.redirect,
       menu.component,
       menu.sorting_order,
       menu.pinned,
       menu.show_tab,
       menu.enable_multi_tab,
       menu.menu_type,
       menu.hidden,
       menu.hide_children_in_menu,
       menu.flat_menu,
       menu.active_menu,
       menu.external,
       menu.target
FROM (
    VALUES ('iam', FALSE, NULL, 'ph:user-list', 'user', '用户管理', TRUE, '/iam/user', 'user', NULL,
            'iam/user/index', 0, FALSE, TRUE, FALSE, 'menu', FALSE, FALSE, FALSE, NULL, FALSE, NULL),
           ('iam', FALSE, NULL, 'ph:person-light', 'role', '角色管理', TRUE, '/iam/role', 'role', NULL,
            'iam/role/index', 0, FALSE, TRUE, FALSE, 'menu', FALSE, FALSE, FALSE, NULL, FALSE, NULL),
           ('iam', FALSE, NULL, 'ph:function-bold', 'menu', '菜单管理', TRUE, '/iam/menu', 'menu', NULL,
            'iam/menu/index', 0, FALSE, TRUE, FALSE, 'menu', FALSE, FALSE, FALSE, NULL, FALSE, NULL),
           ('iam', FALSE, NULL, 'ph:key-bold', 'permission', '权限管理', TRUE, '/iam/permission', 'permission',
            NULL, 'iam/permission/index', 0, FALSE, TRUE, FALSE, 'menu', FALSE, FALSE, FALSE, NULL, FALSE, NULL),
           ('catalog', FALSE, NULL, 'game-icons:barbed-star', 'type', '属性管理', TRUE, '/catalog/type', 'type', NULL,
            'catalog/type/index', 0, FALSE, TRUE, FALSE, 'menu', FALSE, FALSE, FALSE, NULL, FALSE, NULL),
           ('catalog', FALSE, NULL, 'game-icons:beveled-star', 'type-effectiveness', '属性克制管理', TRUE,
            '/catalog/type-effectiveness', 'type-effectiveness', NULL, 'catalog/type-effectiveness/index', 0, FALSE,
            TRUE, FALSE, 'menu', FALSE, FALSE, FALSE, NULL, FALSE, NULL),
           ('catalog', FALSE, NULL, 'game-icons:aura', 'ability', '特性管理', TRUE, '/catalog/ability', 'ability', NULL,
            'catalog/ability/index', 0, FALSE, TRUE, FALSE, 'menu', FALSE, FALSE, FALSE, NULL, FALSE, NULL),
           ('catalog', FALSE, NULL, 'game-icons:growth', 'growth-rate', '成长速率管理', TRUE, '/catalog/growth-rate',
            'growth-rate', NULL, 'catalog/growth-rate/index', 0, FALSE, TRUE, FALSE, 'menu', FALSE, FALSE, FALSE,
            NULL, FALSE, NULL),
           ('catalog', FALSE, NULL, 'game-icons:yin-yang', 'nature', '性格管理', TRUE, '/catalog/nature', 'nature', NULL,
            'catalog/nature/index', 0, FALSE, TRUE, FALSE, 'menu', FALSE, FALSE, FALSE, NULL, FALSE, NULL),
           ('catalog', FALSE, NULL, 'ph:first-aid-kit-bold', 'move-ailment', '招式异常管理', TRUE,
            '/catalog/move-ailment', 'move-ailment', NULL, 'catalog/move-ailment/index', 0, FALSE, TRUE, FALSE,
            'menu', FALSE, FALSE, FALSE, NULL, FALSE, NULL),
           ('catalog', FALSE, NULL, 'ph:squares-four-bold', 'move-category', '招式类别管理', TRUE,
            '/catalog/move-category', 'move-category', NULL, 'catalog/move-category/index', 0, FALSE, TRUE, FALSE,
            'menu', FALSE, FALSE, FALSE, NULL, FALSE, NULL),
           ('catalog', FALSE, NULL, 'ph:graduation-cap-bold', 'move-learn-method', '招式学习方式管理', TRUE,
            '/catalog/move-learn-method', 'move-learn-method', NULL, 'catalog/move-learn-method/index', 0, FALSE,
            TRUE, FALSE, 'menu', FALSE, FALSE, FALSE, NULL, FALSE, NULL),
           ('catalog', FALSE, NULL, 'ph:crosshair-bold', 'move-target', '招式目标管理', TRUE, '/catalog/move-target',
            'move-target', NULL, 'catalog/move-target/index', 0, FALSE, TRUE, FALSE, 'menu', FALSE, FALSE, FALSE,
            NULL, FALSE, NULL),
           ('catalog', FALSE, NULL, 'ph:cube-bold', 'item', '道具管理', TRUE, '/catalog/item', 'item', NULL,
            'catalog/item/index', 0, FALSE, TRUE, FALSE, 'menu', FALSE, FALSE, FALSE, NULL, FALSE, NULL),
           ('catalog', FALSE, NULL, 'ph:sword-bold', 'move', '招式管理', TRUE, '/catalog/move', 'move', NULL,
            'catalog/move/index', 0, FALSE, TRUE, FALSE, 'menu', FALSE, FALSE, FALSE, NULL, FALSE, NULL),
           ('catalog', FALSE, NULL, 'ph:dna-bold', 'species', '精灵种族管理', TRUE, '/catalog/species',
            'species', NULL, 'catalog/species/index', 0, FALSE, TRUE, FALSE, 'menu', FALSE, FALSE,
            FALSE, NULL, FALSE, NULL),
           ('catalog', FALSE, NULL, 'ph:git-merge-bold', 'species-evolution', '进化条件管理', TRUE,
            '/catalog/species-evolution', 'species-evolution', NULL, 'catalog/species-evolution/index', 0, FALSE,
            TRUE, FALSE, 'menu', FALSE, FALSE, FALSE, NULL, FALSE, NULL)
) AS menu(
    parent_menu_key,
    disabled,
    extra,
    icon,
    menu_key,
    title,
    visible,
    path,
    route_name,
    redirect,
    component,
    sorting_order,
    pinned,
    show_tab,
    enable_multi_tab,
    menu_type,
    hidden,
    hide_children_in_menu,
    flat_menu,
    active_menu,
    external,
    target
)
JOIN iam.menu parent ON parent.menu_key = menu.parent_menu_key;

INSERT INTO iam.permission (menu_id, code, name, enabled, sorting_order)
SELECT menu.id, permission.code, permission.name, permission.enabled, permission.sorting_order
FROM (
    VALUES ('user', 'iam:user:query', '查看用户', TRUE, 0),
           ('user', 'iam:user:create', '新增用户', TRUE, 1),
           ('user', 'iam:user:update', '编辑用户', TRUE, 2),
           ('user', 'iam:user:delete', '删除用户', TRUE, 3),
           ('role', 'iam:role:query', '查看角色', TRUE, 0),
           ('role', 'iam:role:create', '新增角色', TRUE, 1),
           ('role', 'iam:role:update', '编辑角色', TRUE, 2),
           ('role', 'iam:role:delete', '删除角色', TRUE, 3),
           ('menu', 'iam:menu:query', '查看菜单', TRUE, 0),
           ('menu', 'iam:menu:create', '新增菜单', TRUE, 1),
           ('menu', 'iam:menu:update', '编辑菜单', TRUE, 2),
           ('menu', 'iam:menu:delete', '删除菜单', TRUE, 3),
           ('permission', 'iam:permission:query', '查看权限点', TRUE, 0),
           ('permission', 'iam:permission:create', '新增权限点', TRUE, 1),
           ('permission', 'iam:permission:update', '编辑权限点', TRUE, 2),
           ('permission', 'iam:permission:delete', '删除权限点', TRUE, 3),
           ('type', 'catalog:type:query', '查看属性', TRUE, 0),
           ('type', 'catalog:type:create', '新增属性', TRUE, 1),
           ('type', 'catalog:type:update', '编辑属性', TRUE, 2),
           ('type', 'catalog:type:delete', '删除属性', TRUE, 3),
           ('type-effectiveness', 'catalog:type-effectiveness:query', '查看属性克制', TRUE, 0),
           ('type-effectiveness', 'catalog:type-effectiveness:create', '新增属性克制', TRUE, 1),
           ('type-effectiveness', 'catalog:type-effectiveness:update', '编辑属性克制', TRUE, 2),
           ('type-effectiveness', 'catalog:type-effectiveness:delete', '删除属性克制', TRUE, 3),
           ('ability', 'catalog:ability:query', '查看特性', TRUE, 0),
           ('ability', 'catalog:ability:create', '新增特性', TRUE, 1),
           ('ability', 'catalog:ability:update', '编辑特性', TRUE, 2),
           ('ability', 'catalog:ability:delete', '删除特性', TRUE, 3),
           ('growth-rate', 'catalog:growth-rate:query', '查看成长速率', TRUE, 0),
           ('growth-rate', 'catalog:growth-rate:create', '新增成长速率', TRUE, 1),
           ('growth-rate', 'catalog:growth-rate:update', '编辑成长速率', TRUE, 2),
           ('growth-rate', 'catalog:growth-rate:delete', '删除成长速率', TRUE, 3),
           ('nature', 'catalog:nature:query', '查看性格', TRUE, 0),
           ('nature', 'catalog:nature:create', '新增性格', TRUE, 1),
           ('nature', 'catalog:nature:update', '编辑性格', TRUE, 2),
           ('nature', 'catalog:nature:delete', '删除性格', TRUE, 3),
           ('move-ailment', 'catalog:move-ailment:query', '查看招式异常', TRUE, 0),
           ('move-ailment', 'catalog:move-ailment:create', '新增招式异常', TRUE, 1),
           ('move-ailment', 'catalog:move-ailment:update', '编辑招式异常', TRUE, 2),
           ('move-ailment', 'catalog:move-ailment:delete', '删除招式异常', TRUE, 3),
           ('move-category', 'catalog:move-category:query', '查看招式类别', TRUE, 0),
           ('move-category', 'catalog:move-category:create', '新增招式类别', TRUE, 1),
           ('move-category', 'catalog:move-category:update', '编辑招式类别', TRUE, 2),
           ('move-category', 'catalog:move-category:delete', '删除招式类别', TRUE, 3),
           ('move-learn-method', 'catalog:move-learn-method:query', '查看招式学习方式', TRUE, 0),
           ('move-learn-method', 'catalog:move-learn-method:create', '新增招式学习方式', TRUE, 1),
           ('move-learn-method', 'catalog:move-learn-method:update', '编辑招式学习方式', TRUE, 2),
           ('move-learn-method', 'catalog:move-learn-method:delete', '删除招式学习方式', TRUE, 3),
           ('move-target', 'catalog:move-target:query', '查看招式目标', TRUE, 0),
           ('move-target', 'catalog:move-target:create', '新增招式目标', TRUE, 1),
           ('move-target', 'catalog:move-target:update', '编辑招式目标', TRUE, 2),
           ('move-target', 'catalog:move-target:delete', '删除招式目标', TRUE, 3),
           ('item', 'catalog:item:query', '查看道具', TRUE, 0),
           ('item', 'catalog:item:create', '新增道具', TRUE, 1),
           ('item', 'catalog:item:update', '编辑道具', TRUE, 2),
           ('item', 'catalog:item:delete', '删除道具', TRUE, 3),
           ('move', 'catalog:move:query', '查看招式', TRUE, 0),
           ('move', 'catalog:move:create', '新增招式', TRUE, 1),
           ('move', 'catalog:move:update', '编辑招式', TRUE, 2),
           ('move', 'catalog:move:delete', '删除招式', TRUE, 3),
           ('species', 'catalog:species:query', '查看精灵种族', TRUE, 0),
           ('species', 'catalog:species:create', '新增精灵种族', TRUE, 1),
           ('species', 'catalog:species:update', '编辑精灵种族', TRUE, 2),
           ('species', 'catalog:species:delete', '删除精灵种族', TRUE, 3),
           ('species', 'catalog:species-ability:query', '查看精灵特性', TRUE, 4),
           ('species', 'catalog:species-ability:create', '新增精灵特性', TRUE, 5),
           ('species', 'catalog:species-ability:update', '编辑精灵特性', TRUE, 6),
           ('species', 'catalog:species-ability:delete', '删除精灵特性', TRUE, 7),
           ('species', 'catalog:species-move-learnset:query', '查看精灵招式学习集', TRUE, 8),
           ('species', 'catalog:species-move-learnset:create', '新增精灵招式学习集', TRUE, 9),
           ('species', 'catalog:species-move-learnset:update', '编辑精灵招式学习集', TRUE, 10),
           ('species', 'catalog:species-move-learnset:delete', '删除精灵招式学习集', TRUE, 11),
           ('species-evolution', 'catalog:species-evolution:query', '查看进化条件', TRUE, 0),
           ('species-evolution', 'catalog:species-evolution:create', '新增进化条件', TRUE, 1),
           ('species-evolution', 'catalog:species-evolution:update', '编辑进化条件', TRUE, 2),
           ('species-evolution', 'catalog:species-evolution:delete', '删除进化条件', TRUE, 3)
) AS permission(menu_key, code, name, enabled, sorting_order)
JOIN iam.menu menu ON menu.menu_key = permission.menu_key;

INSERT INTO iam.role_menu (role_id, menu_id)
SELECT role.id, menu.id
FROM iam.role role
JOIN iam.menu menu ON TRUE
WHERE role.code = 'ROLE_SUPER_ADMIN';

INSERT INTO iam.role_permission (role_id, permission_id)
SELECT role.id, permission.id
FROM iam.role role
JOIN iam.permission permission ON TRUE
WHERE role.code = 'ROLE_SUPER_ADMIN';
