name: Build With Maven

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21 for x64
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: oracle
          architecture: x64
          cache: maven
      - name: Build with Maven
        run: mvn package